//! The NVFP4 matvec for one to four tokens, for Metal: `y = x Wᵀ (+ r)` for
//! a decode step and for the 2-4 tokens a speculative verify feeds.
//!
//! A decode step reads the weights at the memory roof. A verify of three
//! tokens reads the same weights once and should cost about the same; the
//! batched kernel it went through cost 1.18x a step in its matvecs (gate/up
//! 128 against 110 us a call on an M4 Max), which was most of why a verify
//! cost 1.21 steps. Here each lane decodes its sixteen weights once and runs
//! them against every token's sixteen inputs, one accumulator per (token,
//! row), in the structure the one-token kernel reads fastest with: two rows
//! a simdgroup, a run of sixteen summed unscaled and scaled once. Measured
//! at the gate/up shape (`examples/mv_metal --tokens T`):
//!
//! ```text
//!   tokens        2      3      4      5      6      8
//!   batched     119    128    147    168    186    230   us a call
//!   this        101    105    116    153    192    228
//! ```
//!
//! Past four tokens the accumulators cost more than the shared read saves,
//! and a verify never has more than four (`SPEC_MAX`), so the runtime takes
//! this for 1-4 and the batched kernel beyond.
//!
//! At one token it is the decode matvec: 103.8 us a call against the
//! emitted kernel's 110.3 at gate/up (97.6 against 103.9 with independent
//! calls overlapping, which is how MLX's 96 was timed), so a decode step
//! reads its weights at the rate MLX's does.
//!
//! **Hand-scheduled, like `crate::gemm`**, and for the same reason; it
//! takes exactly the parameters `lex_front::llama::matmul_q_x` does, in the
//! same order, so a runtime binds either one the same way.

use crate::dialect::{Dialect, Msl};
use crate::program::Lowered;

/// How the rows are spread: rows a simdgroup, simdgroups a threadgroup.
///
/// The default is what the gate/up shape measured best on an M4 Max; other
/// shapes and other chips may want another, which is what
/// `lex_rt::tune` finds on the device (`matvec_few_nvfp4_with`).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Layout {
    pub rows: usize,
    pub simdgroups: usize,
}

impl Default for Layout {
    fn default() -> Self {
        Layout {
            rows: 2,
            simdgroups: 2,
        }
    }
}

/// The layouts worth trying: one to four rows a simdgroup, one to eight
/// simdgroups a threadgroup.
pub fn layouts() -> Vec<Layout> {
    let mut v = vec![];
    for rows in [1, 2, 4] {
        for simdgroups in [1, 2, 4, 8] {
            v.push(Layout { rows, simdgroups });
        }
    }
    v
}

/// The shape and the activations' type.
#[derive(Clone, Copy, Debug)]
pub struct Few {
    pub tokens: usize,
    pub n: usize,
    pub k: usize,
    pub residual: bool,
    pub x_half: bool,
}

/// Whether `f` fits: 1-4 tokens, whole groups of 16 inputs.
pub fn fits(f: &Few) -> bool {
    (1..=4).contains(&f.tokens) && f.n > 0 && f.k > 0 && f.k.is_multiple_of(16)
}

pub fn matvec_few_nvfp4(f: &Few) -> Result<Lowered, String> {
    matvec_few_nvfp4_with(f, Layout::default())
}

/// [`matvec_few_nvfp4`] with its rows spread as `layout` says. Every layout
/// computes the same sums in the same order a row, so they agree exactly.
pub fn matvec_few_nvfp4_with(f: &Few, layout: Layout) -> Result<Lowered, String> {
    let (r, sg) = (layout.rows, layout.simdgroups);
    if r == 0 || sg == 0 || 32 * sg > 1024 {
        return Err(format!("matvec_few: layout {layout:?}"));
    }
    if !fits(f) {
        return Err(format!(
            "matvec_few: {} tokens (1-4), {} inputs (whole groups of 16)",
            f.tokens, f.k
        ));
    }
    let entry = format!(
        "matvec_few_nvfp4_{}x{}x{}{}{}_r{r}s{sg}",
        f.tokens,
        f.n,
        f.k,
        if f.residual { "_res" } else { "" },
        if f.x_half { "_xh" } else { "" }
    );
    let (xt, x4) = if f.x_half {
        ("half", "half4")
    } else {
        ("float", "float4")
    };
    let (rparam, ybuf, radd) = if f.residual {
        (
            "    device const float *r [[buffer(4)]],\n",
            5,
            " + r[j * N + row]",
        )
    } else {
        ("", 4, "")
    };
    let per_tg = r * sg;
    let source = format!(
        r#"// Generated by lex-msl::few. Hand-scheduled, not lowered from a program.
// kernel : {entry}
// launch : {grid} threadgroups x {threads} threads, {r} rows a simdgroup
{includes}{fp4}
kernel void {entry}(
    device const {xt} *x [[buffer(0)]],
    device const uchar *q [[buffer(1)]],
    device const uchar *s [[buffer(2)]],
    device const float *gs [[buffer(3)]],
{rparam}    device float *y [[buffer({ybuf})]],
    uint3 tg [[threadgroup_position_in_grid]],
    uint sgid [[simdgroup_index_in_threadgroup]],
    uint lane [[thread_index_in_simdgroup]])
{{
    const uint N = {n}u, K = {k}u;
    const uint row0 = (tg.x * {sg}u + sgid) * {r}u;
    if (row0 >= N) return;
    float acc[{t}][{r}];
    for (uint j = 0; j < {t}u; ++j)
        for (uint i = 0; i < {r}u; ++i) acc[j][i] = 0.0f;
    for (uint p0 = lane * 16u; p0 < K; p0 += 512u) {{
        #pragma unroll
        for (uint i = 0; i < {r}u; ++i) {{
            const uint row = min(row0 + i, N - 1u);
            const uint2 w = *(const device uint2 *)(q + row * (K / 2u) + p0 / 2u);
            const float sc = fp8_e4m3(s[row * (K / 16u) + p0 / 16u]);
            const float2 v0 = fp4_pair(w.x & 0xFFu), v1 = fp4_pair((w.x >> 8u) & 0xFFu),
                         v2 = fp4_pair((w.x >> 16u) & 0xFFu), v3 = fp4_pair(w.x >> 24u),
                         v4 = fp4_pair(w.y & 0xFFu), v5 = fp4_pair((w.y >> 8u) & 0xFFu),
                         v6 = fp4_pair((w.y >> 16u) & 0xFFu), v7 = fp4_pair(w.y >> 24u);
            #pragma unroll
            for (uint j = 0; j < {t}u; ++j) {{
                const device {x4} *xp = (const device {x4} *)(x + j * K + p0);
                const float4 x0 = float4(xp[0]), x1 = float4(xp[1]), x2 = float4(xp[2]), x3 = float4(xp[3]);
                // A run of sixteen, summed unscaled, then its group's scale.
                const float run = x0.x * v0.x + x0.y * v0.y + x0.z * v1.x + x0.w * v1.y
                                + x1.x * v2.x + x1.y * v2.y + x1.z * v3.x + x1.w * v3.y
                                + x2.x * v4.x + x2.y * v4.y + x2.z * v5.x + x2.w * v5.y
                                + x3.x * v6.x + x3.y * v6.y + x3.z * v7.x + x3.w * v7.y;
                acc[j][i] += run * sc;
            }}
        }}
    }}
    // The row's scale, and the 16384 that undoes `fp4_pair`'s bias.
    for (uint i = 0; i < {r}u; ++i) {{
        const uint row = row0 + i;
        for (uint j = 0; j < {t}u; ++j) {{
            const float v = simd_sum(acc[j][i]);
            if (lane == 0u && row < N) y[j * N + row] = v * gs[row] * 16384.0f{radd};
        }}
    }}
}}
"#,
        includes = Msl.includes(),
        fp4 = Msl.fp4_preamble(),
        n = f.n,
        k = f.k,
        t = f.tokens,
        grid = f.n.div_ceil(per_tg),
        threads = 32 * sg,
    );
    let mut writes = vec![false; 4];
    if f.residual {
        writes.push(false);
    }
    writes.push(true);
    Ok(Lowered {
        entry,
        source,
        grid: f.n.div_ceil(per_tg),
        grid2: 1,
        threads: 32 * sg,
        threadgroup_bytes: 0,
        arena_bytes: 0,
        scratch_bytes: 0,
        barriers: 0,
        writes,
    })
}
