//! A tiled GEMM on the matrix units, for NVFP4 weights: `y = x Wᵀ (+ r)`.
//!
//! Prefill reads every weight once per chunk of tokens. The batched matvec
//! that serves a verify's few tokens keeps an accumulator per (row, token)
//! in registers, so its chunk cannot grow past about 16 before it spills
//! and collapses (258 ms/token at 32, `docs/roadmap-weeks.md` M3c) -- and at
//! 8 a 512-token prompt reads the 14.5 GB of weights sixty-four times. A
//! GEMM keeps the accumulators in the matrix units' fragments instead, so
//! the chunk can be 64 or 128 tokens and the weights are read that many
//! fewer times.
//!
//! **This kernel is hand-scheduled, not lowered from a `lex-front`
//! program**, like the P0 copy and RMSNorm. The IR has the operation
//! (`MatMulNT` against lazily dequantised weights) but no matrix fragments
//! yet, and `docs/roadmap-weeks.md` already says the GEMM should be made
//! fast as a kernel before it is made expressible. It takes exactly the
//! parameters `lex_front::llama::matmul_q_x` does, in the same order, so a
//! runtime binds either one the same way and can choose per chunk size.
//!
//! One source per backend, same tiling idea: stage a tile of activations
//! and a tile of weights -- dequantised to half on the way into shared
//! memory, which is what makes NVFP4 and the matrix units compatible at
//! all -- multiply-accumulate in fragments, and write back through shared
//! memory so partial tiles can be guarded.
//! - CUDA: `wmma` 16x16x16, 64x64 tiles, four warps of 32x32.
//! - Metal: `simdgroup_matrix` 8x8, 32x32 tiles, four simdgroups of 16x16,
//!   the kernel `examples/gemm_probe` measured.

use crate::dialect::{Cuda, Dialect, Msl};
use crate::program::Lowered;

/// Which matrix units to write for.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Backend {
    Metal,
    Cuda,
}

/// A GEMM's shape: `m` tokens, `n` output rows, `k` inputs.
#[derive(Clone, Copy, Debug)]
pub struct Gemm {
    pub m: usize,
    pub n: usize,
    pub k: usize,
    /// Add `r` (the residual) to the product, as the matmuls writing back
    /// into the stream do.
    pub residual: bool,
    /// The activations are half rather than f32.
    pub x_half: bool,
}

/// The K tile, and so the granularity `k` has to meet.
const BK: usize = 32;

/// Whether `g` can go through [`gemm_nvfp4`] at all. Output rows and tokens
/// may be ragged (they are guarded); the reduction may not.
pub fn fits(g: &Gemm) -> bool {
    g.m > 0 && g.n > 0 && g.k.is_multiple_of(BK)
}

pub fn gemm_nvfp4(g: &Gemm, backend: Backend) -> Result<Lowered, String> {
    if !fits(g) {
        return Err(format!(
            "gemm {}x{}x{}: the reduction must be a multiple of {BK}",
            g.m, g.n, g.k
        ));
    }
    let entry = format!(
        "gemm_nvfp4_{}x{}x{}{}{}",
        g.m,
        g.n,
        g.k,
        if g.residual { "_res" } else { "" },
        if g.x_half { "_xh" } else { "" }
    );
    let mut writes = vec![false; 4];
    if g.residual {
        writes.push(false);
    }
    writes.push(true);
    Ok(match backend {
        Backend::Cuda => cuda(g, entry, writes),
        Backend::Metal => metal(g, entry, writes),
    })
}

fn cuda(g: &Gemm, entry: String, writes: Vec<bool>) -> Lowered {
    let (bn, threads) = (64usize, 128usize);
    // A chunk of 16 or 32 tokens would spend most of a 64-row tile on
    // padding; halve the tile instead.
    let bm = if g.m <= 32 { 32 } else { 64 };
    // Four warps as 2x2, each owning a (bm/2) x (bn/2) block of 16x16
    // fragments.
    let (wtm, wtn) = (bm / 2, bn / 2);
    let (fm, fnn) = (wtm / 16, wtn / 16);
    // Rows padded by 8 halves (16 bytes): off the bank a column read would
    // otherwise hit every time, and still a multiple of the 16 bytes
    // `load_matrix_sync` requires of its stride.
    let (bkp, bnp) = (BK + 8, bn + 4);
    let xt = if g.x_half { "__half" } else { "float" };
    let to_half = if g.x_half { "{v}" } else { "__float2half({v})" };
    let xload = to_half.replace("{v}", "x[(m0 + rr) * K + k0 + c]");
    let rparam = if g.residual {
        "    const float* __restrict__ r,\n"
    } else {
        ""
    };
    let radd = if g.residual {
        " + r[(m0 + rr) * N + n0 + c]"
    } else {
        ""
    };
    let (m, n, k) = (g.m, g.n, g.k);
    let source = format!(
        r#"// Generated by lex-msl::gemm. Hand-scheduled, not lowered from a program.
// kernel : {entry}
// launch : {gx} x {gy} blocks x {threads} threads
{includes}#include <mma.h>

{fp4}
extern "C" __global__ void {entry}(
    const {xt}* __restrict__ x,
    const char* __restrict__ q,
    const char* __restrict__ s,
    const float* __restrict__ gs,
{rparam}    float* __restrict__ y
)
{{
    using namespace nvcuda;
    const uint M = {m}u, N = {n}u, K = {k}u;
    const uint tid = threadIdx.x, warp = tid / 32u;
    const uint n0 = blockIdx.x * {bn}u, m0 = blockIdx.y * {bm}u;
    const uint wm = warp / 2u, wn = warp % 2u;
    __shared__ __align__(32) __half As[{bm}][{bkp}];
    __shared__ __align__(32) __half Bs[{bn}][{bkp}];
    __shared__ __align__(32) float Cs[{bm}][{bnp}];

    wmma::fragment<wmma::accumulator, 16, 16, 16, float> acc[{fm}][{fnn}];
    for (int i = 0; i < {fm}; ++i)
        for (int j = 0; j < {fnn}; ++j) wmma::fill_fragment(acc[i][j], 0.0f);

    for (uint k0 = 0; k0 < K; k0 += {bk}u) {{
        // Activations: a {bm} x {bk} tile, zero past the last token.
        for (uint e = tid; e < {bm}u * {bk}u; e += {threads}u) {{
            const uint rr = e / {bk}u, c = e % {bk}u;
            As[rr][c] = (m0 + rr < M) ? {xload} : __float2half(0.0f);
        }}
        // Weights, dequantised: one thread per group of 16, so the FP8
        // scale is decoded once per group, and its 8 bytes are one load.
        // `fp4_pair` leaves values 2^14 small; the 2^14 rides on the scale.
        for (uint gi = tid; gi < {bn}u * {bk}u / 16u; gi += {threads}u) {{
            const uint rr = gi / ({bk}u / 16u), c0 = (gi % ({bk}u / 16u)) * 16u;
            const uint j = n0 + rr;
            if (j < N) {{
                const float sc = fp8_e4m3((uint)(uchar)s[j * (K / 16u) + (k0 + c0) / 16u])
                    * gs[j] * 16384.0f;
                const uint2 w = *reinterpret_cast<const uint2*>(&q[j * (K / 2u) + (k0 + c0) / 2u]);
                for (uint b = 0; b < 8u; ++b) {{
                    const float2 v = fp4_pair(((b < 4u ? w.x : w.y) >> (8u * (b & 3u))) & 0xFFu);
                    Bs[rr][c0 + 2u * b] = __float2half(v.x * sc);
                    Bs[rr][c0 + 2u * b + 1u] = __float2half(v.y * sc);
                }}
            }} else {{
                for (uint c = 0; c < 16u; ++c) Bs[rr][c0 + c] = __float2half(0.0f);
            }}
        }}
        __syncthreads();
        for (uint kk = 0; kk < {bk}u; kk += 16u) {{
            wmma::fragment<wmma::matrix_a, 16, 16, 16, __half, wmma::row_major> a[{fm}];
            // Bs is [row][k]: as a K x N matrix that is column-major.
            wmma::fragment<wmma::matrix_b, 16, 16, 16, __half, wmma::col_major> b[{fnn}];
            for (int i = 0; i < {fm}; ++i)
                wmma::load_matrix_sync(a[i], &As[wm * {wtm}u + i * 16u][kk], {bkp});
            for (int j = 0; j < {fnn}; ++j)
                wmma::load_matrix_sync(b[j], &Bs[wn * {wtn}u + j * 16u][kk], {bkp});
            for (int i = 0; i < {fm}; ++i)
                for (int j = 0; j < {fnn}; ++j) wmma::mma_sync(acc[i][j], a[i], b[j], acc[i][j]);
        }}
        __syncthreads();
    }}

    // Through shared memory, so ragged tokens and rows can be left out.
    for (int i = 0; i < {fm}; ++i)
        for (int j = 0; j < {fnn}; ++j)
            wmma::store_matrix_sync(&Cs[wm * {wtm}u + i * 16u][wn * {wtn}u + j * 16u],
                                    acc[i][j], {bnp}, wmma::mem_row_major);
    __syncthreads();
    for (uint e = tid; e < {bm}u * {bn}u; e += {threads}u) {{
        const uint rr = e / {bn}u, c = e % {bn}u;
        if (m0 + rr < M && n0 + c < N) y[(m0 + rr) * N + n0 + c] = Cs[rr][c]{radd};
    }}
}}
"#,
        includes = Cuda.includes(),
        fp4 = Cuda.fp4_preamble(),
        gx = n.div_ceil(bn),
        gy = m.div_ceil(bm),
        bk = BK,
    );
    Lowered {
        entry,
        source,
        grid: n.div_ceil(bn),
        grid2: m.div_ceil(bm),
        threads,
        threadgroup_bytes: 2 * bm * bkp + 2 * bn * bkp + 4 * bm * bnp,
        arena_bytes: 0,
        scratch_bytes: 0,
        barriers: 3,
        writes,
    }
}

fn metal(g: &Gemm, entry: String, writes: Vec<bool>) -> Lowered {
    // The tile: 32 tokens by 64 rows, measured rather than reasoned. At 128
    // tokens a chunk, 512-token prefill on an M4 Max (tok/s, gate/up ms a
    // call):
    //
    //   tokens x rows   32x32  64x32  128x32  64x64  32x64  32x128
    //   tok/s            100    82     67     101    123    120
    //   gate/up ms       3.4    4.0    6.1    3.7    2.6    2.8
    //
    // Taller token tiles dequantise each weight fewer times and are
    // *slower*; wider weight tiles are faster. At 32x64 the staging loop has
    // exactly one 16-value group for each of the 128 threads, where 32x32
    // left half of them idle. The staging tiles and the output tile share
    // one buffer (the output is only written after the last multiply),
    // which took 64x64 from 72 tok/s to 101: occupancy, as ever. 64x128
    // does not fit the 32 KB a threadgroup may declare.
    // `LEX_GEMM_BM` (tokens) and `LEX_GEMM_BN` (rows) to measure others.
    let pick = |var: &str, default: usize| {
        std::env::var(var)
            .ok()
            .and_then(|v| v.parse::<usize>().ok())
            .filter(|t| [32, 64, 128].contains(t))
            .unwrap_or(default)
    };
    let (bm, bn, threads) = (pick("LEX_GEMM_BM", 32), pick("LEX_GEMM_BN", 64), 128usize);
    // The K step: 32. Twice the depth a step halves the barriers and was
    // measured slower at 32x64 -- prefill 112-119 tok/s against 123, gate/up
    // unchanged at 2.64 ms -- as it was at 32x32 in `gemm_probe`.
    // `LEX_GEMM_BK=64` keeps it for measuring, where the reduction allows.
    let bk = match std::env::var("LEX_GEMM_BK")
        .ok()
        .and_then(|v| v.parse::<usize>().ok())
    {
        Some(64) if g.k.is_multiple_of(64) => 64,
        _ => BK,
    };
    // Four simdgroups as 2x2, each (bm/2) rows by (bn/2) columns of 8x8.
    let (fm, nf) = ((bm / 2) / 8, (bn / 2) / 8);
    let (bkp, bnp) = (bk + 4, bn + 4);
    // One buffer, in floats: the two half tiles while the loop runs, then
    // the float output tile.
    let staged = (bm * bkp + bn * bkp).div_ceil(2);
    let words = staged.max(bm * bnp);
    let xt = if g.x_half { "half" } else { "float" };
    let rparam = if g.residual {
        "    device const float *r [[buffer(4)]],\n"
    } else {
        ""
    };
    let ybuf = if g.residual { 5 } else { 4 };
    let radd = if g.residual {
        " + r[(m0 + rr) * N + j0 + c]"
    } else {
        ""
    };
    let (m, n, k) = (g.m, g.n, g.k);
    let source = format!(
        r#"// Generated by lex-msl::gemm. Hand-scheduled, not lowered from a program.
// kernel : {entry}
// launch : {gx} x {gy} threadgroups x {threads} threads, tile {bm}x{bn}
{includes}#include <metal_simdgroup_matrix>

{fp4}
kernel void {entry}(
    device const {xt} *x [[buffer(0)]],
    device const char *q [[buffer(1)]],
    device const char *s [[buffer(2)]],
    device const float *gs [[buffer(3)]],
{rparam}    device float *y [[buffer({ybuf})]],
    uint3 tgpos [[threadgroup_position_in_grid]],
    uint tid [[thread_index_in_threadgroup]],
    uint sgid [[simdgroup_index_in_threadgroup]])
{{
    const uint M = {m}u, N = {n}u, K = {k}u;
    threadgroup float buf[{words}];
    threadgroup half *As = (threadgroup half *)buf;       // [{bm}][{bkp}]
    threadgroup half *Bs = As + {bm}u * {bkp}u;            // [{bn}][{bkp}]
    threadgroup float *Cs = buf;                           // [{bm}][{bnp}], after the loop
    const uint j0 = tgpos.x * {bn}u, m0 = tgpos.y * {bm}u;
    const uint wm = sgid / 2u, wn = sgid % 2u;

    simdgroup_matrix<float, 8, 8> acc[{fm}][{nf}];
    for (uint a = 0; a < {fm}u; ++a)
        for (uint b = 0; b < {nf}u; ++b) acc[a][b] = simdgroup_matrix<float, 8, 8>(0.0f);

    for (uint p0 = 0; p0 < K; p0 += {bk}u) {{
        for (uint e = tid; e < {bm}u * {bk}u; e += {threads}u) {{
            const uint rr = e / {bk}u, c = e % {bk}u;
            As[rr * {bkp}u + c] = (m0 + rr < M) ? half(x[(m0 + rr) * K + p0 + c]) : half(0.0h);
        }}
        // One thread per group of 16: the FP8 scale once, then 8 bytes.
        for (uint gi = tid; gi < {bn}u * {bk}u / 16u; gi += {threads}u) {{
            const uint rr = gi / ({bk}u / 16u), c0 = (gi % ({bk}u / 16u)) * 16u;
            const uint j = j0 + rr;
            threadgroup half *row = Bs + rr * {bkp}u + c0;
            if (j < N) {{
                const float sc = fp8_e4m3((uint)(uchar)s[j * (K / 16u) + (p0 + c0) / 16u])
                    * gs[j] * 16384.0f;
                const uint base = j * (K / 2u) + (p0 + c0) / 2u;
                for (uint b = 0; b < 8u; ++b) {{
                    const float2 v = fp4_pair((uint)(uchar)q[base + b]);
                    row[2u * b] = half(v.x * sc);
                    row[2u * b + 1u] = half(v.y * sc);
                }}
            }} else {{
                for (uint c = 0; c < 16u; ++c) row[c] = half(0.0h);
            }}
        }}
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint kk = 0; kk < {bk}u; kk += 8u) {{
            simdgroup_matrix<half, 8, 8> a[{fm}], b[{nf}];
            for (uint i = 0; i < {fm}u; ++i)
                simdgroup_load(a[i], As + (wm * {fm8}u + i * 8u) * {bkp}u + kk, {bkp});
            // Bs is [row][k]; the fragment wants it transposed.
            for (uint i = 0; i < {nf}u; ++i)
                simdgroup_load(b[i], Bs + (wn * {nf8}u + i * 8u) * {bkp}u + kk, {bkp},
                               ulong2(0, 0), true);
            for (uint i = 0; i < {fm}u; ++i)
                for (uint jj = 0; jj < {nf}u; ++jj)
                    simdgroup_multiply_accumulate(acc[i][jj], a[i], b[jj], acc[i][jj]);
        }}
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }}

    // The staging tiles are dead: the loop ended on a barrier.
    for (uint i = 0; i < {fm}u; ++i)
        for (uint jj = 0; jj < {nf}u; ++jj)
            simdgroup_store(acc[i][jj], Cs + (wm * {fm8}u + i * 8u) * {bnp}u + wn * {nf8}u + jj * 8u,
                            {bnp});
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint e = tid; e < {bm}u * {bn}u; e += {threads}u) {{
        const uint rr = e / {bn}u, c = e % {bn}u;
        if (m0 + rr < M && j0 + c < N) y[(m0 + rr) * N + j0 + c] = Cs[rr * {bnp}u + c]{radd};
    }}
}}
"#,
        includes = Msl.includes(),
        fp4 = Msl.fp4_preamble(),
        gx = n.div_ceil(bn),
        gy = m.div_ceil(bm),
        nf8 = nf * 8,
        fm8 = fm * 8,
    );
    Lowered {
        entry,
        source,
        grid: n.div_ceil(bn),
        grid2: m.div_ceil(bm),
        threads,
        threadgroup_bytes: 4 * words,
        arena_bytes: 0,
        scratch_bytes: 0,
        barriers: 3,
        writes,
    }
}
