//! NVFP4 matvec in integer arithmetic, for CUDA: `y = x Wᵀ (+ r)` for a
//! few tokens, weights decoded to int8 and activations quantised to int16.
//!
//! On an L4 the float decode matvec is clock-bound, not bandwidth-bound:
//! it reads 212 GB/s alone and half as long again inside the model, where
//! the 72 W cap holds the SM clock to ~1395 MHz of 2040
//! (`docs/roadmap-weeks.md` M5a). Its cost is instructions per weight
//! byte -- about 100 per 16 weights to decode E2M1 in float and multiply.
//! Here each four E2M1 codes become four int8 values with three
//! `__byte_perm` table lookups, and two products are one `__dp2a` against
//! int16 activations.
//!
//! Int8 activations were tried first -- four products a `__dp4a`, 245 GB/s
//! alone against 213, decode 112 -> 67 ms a token on an L4 -- and moved a
//! golden log-prob by 0.027 against a 0.02 tolerance. Sixteen bits make the
//! activation error ~256x smaller for twice the dot-product instructions,
//! still a fraction of the float path's.
//!
//! **Hand-scheduled, like `crate::gemm`**: the IR has no integer dot
//! product or quantised activation yet. It changes the arithmetic --
//! activations carry 16 bits and one scale per 16 values -- which is why it
//! is gated on the golden suite and switchable at runtime.
//!
//! Two kernels:
//! - [`quant16`]: each row of `x` (f32 or f16) to int16, one f32 scale per
//!   16 values (the largest magnitude over 32767).
//! - [`matmul_int8`]: one warp a weight row; each lane decodes 32 weights at
//!   a time once and multiplies them against every token. Tokens are
//!   independent and summed in the same order whatever `m` is, so a token's
//!   output is bit-identical alone and in a batch -- which a speculative
//!   verify, checked against plain decode, depends on.

use crate::dialect::{Cuda, Dialect};
use crate::program::Lowered;

const THREADS: usize = 256;
const WARPS: usize = THREADS / 32;

/// Whether `k` inputs fit these kernels: whole 32-value chunks per lane step.
pub fn fits(k: usize) -> bool {
    k > 0 && k.is_multiple_of(32)
}

/// `m` rows of `k` values to int16, with one scale per 16.
/// Parameters: `x [m, k]` (f32, or f16 when `x_half`), `xq [m, k]` i16,
/// `xs [m, k / 16]` f32.
pub fn quant16(m: usize, k: usize, x_half: bool) -> Result<Lowered, String> {
    if !fits(k) {
        return Err(format!("quant16: {k} inputs are not whole groups of 32"));
    }
    let groups = m * k / 16;
    let entry = format!("quant16_{m}x{k}{}", if x_half { "_xh" } else { "" });
    let (xt, load) = if x_half {
        (
            "__half",
            // Sixteen halves are 32 bytes: two uint4, eight half2.
            r#"const uint4* xp = reinterpret_cast<const uint4*>(x) + g * 2u;
    const uint4 raw[2] = {xp[0], xp[1]};
    float v[16];
    const __half2* hp = reinterpret_cast<const __half2*>(raw);
    for (int i = 0; i < 8; ++i) {
        const float2 f = __half22float2(hp[i]);
        v[2 * i] = f.x;
        v[2 * i + 1] = f.y;
    }"#,
        )
    } else {
        (
            "float",
            r#"const float4* xp = reinterpret_cast<const float4*>(x) + g * 4u;
    float v[16];
    for (int i = 0; i < 4; ++i) {
        const float4 f = xp[i];
        v[4 * i] = f.x; v[4 * i + 1] = f.y; v[4 * i + 2] = f.z; v[4 * i + 3] = f.w;
    }"#,
        )
    };
    let source = format!(
        r#"// Generated by lex-msl::int8. Hand-scheduled, not lowered from a program.
{includes}
extern "C" __global__ void {entry}(const {xt}* __restrict__ x, short* __restrict__ xq,
                                   float* __restrict__ xs) {{
    const uint g = blockIdx.x * {THREADS}u + threadIdx.x;
    if (g >= {groups}u) return;
    {load}
    float mx = 0.0f;
    for (int i = 0; i < 16; ++i) mx = fmaxf(mx, fabsf(v[i]));
    const float inv = mx > 0.0f ? 32767.0f / mx : 0.0f;
    // Sixteen int16, two to a word: 32 bytes, two uint4.
    uint w[8];
    for (int i = 0; i < 8; ++i)
        w[i] = ((uint)__float2int_rn(v[2 * i] * inv) & 0xFFFFu)
             | (((uint)__float2int_rn(v[2 * i + 1] * inv) & 0xFFFFu) << 16u);
    uint4* out = reinterpret_cast<uint4*>(xq) + g * 2u;
    out[0] = make_uint4(w[0], w[1], w[2], w[3]);
    out[1] = make_uint4(w[4], w[5], w[6], w[7]);
    xs[g] = mx / 32767.0f;
}}
"#,
        includes = Cuda.includes(),
    );
    Ok(Lowered {
        entry,
        source,
        grid: groups.div_ceil(THREADS),
        grid2: 1,
        threads: THREADS,
        threadgroup_bytes: 0,
        arena_bytes: 0,
        scratch_bytes: 0,
        barriers: 0,
        writes: vec![false, true, true],
    })
}

/// `y[i, j] = sum_p x[i, p] * W[j, p] (+ r[i, j])` for `m` tokens against an
/// NVFP4 `W [n, k]`, the tokens given as [`quant16`] leaves them.
/// Parameters: `xq [m, k]` i16, `xs [m, k / 16]` f32, then `W`'s codes,
/// scales and per-row scale as `matmul_q_x` takes them, then `r [m, n]` if
/// `residual`, then `y [m, n]` f32.
pub fn matmul_int8(m: usize, n: usize, k: usize, residual: bool) -> Result<Lowered, String> {
    if !fits(k) || m == 0 || n == 0 {
        return Err(format!("matmul_int8 {m}x{n}x{k}: need k a multiple of 32"));
    }
    let entry = format!(
        "matmul_int8_{m}x{n}x{k}{}",
        if residual { "_res" } else { "" }
    );
    let rparam = if residual {
        "    const float* __restrict__ r,\n"
    } else {
        ""
    };
    let radd = if residual { " + r[i * N + row]" } else { "" };
    let source = format!(
        r#"// Generated by lex-msl::int8. Hand-scheduled, not lowered from a program.
{includes}{fp4}
// Four E2M1 codes (the low 16 bits) to four int8 values, twice the true
// value so they are integers: magnitudes {{0,1,2,3,4,6,8,12}}. A selector
// nibble's low three bits index eight bytes, so one __byte_perm looks the
// magnitudes up in a positive table, one in a negative table, and a third
// picks per byte by the code's sign bit. Checked against the E2M1
// definition for all 65536 inputs.
__device__ __forceinline__ int e2m1x4(uint codes) {{
    const uint idx = codes & 0x7777u;
    const uint pos = __byte_perm(0x03020100u, 0x0C080604u, idx);
    const uint neg = __byte_perm(0xFDFEFF00u, 0xF4F8FAFCu, idx);
    return (int)__byte_perm(pos, neg, 0x3210u | ((codes & 0x8888u) >> 1u));
}}

extern "C" __global__ void {entry}(
    const short* __restrict__ xq,
    const float* __restrict__ xs,
    const char* __restrict__ q,
    const char* __restrict__ s,
    const float* __restrict__ gs,
{rparam}    float* __restrict__ y
)
{{
    const uint M = {m}u, N = {n}u, K = {k}u;
    const uint lane = threadIdx.x & 31u;
    const uint row = blockIdx.x * {WARPS}u + (threadIdx.x >> 5u);
    if (row >= N) return;
    const uint4* qr = reinterpret_cast<const uint4*>(q + (size_t)row * (K / 2u));
    const uchar* sr = reinterpret_cast<const uchar*>(s) + (size_t)row * (K / 16u);
    float acc[{m}];
    for (uint i = 0; i < M; ++i) acc[i] = 0.0f;
    // A lane takes 32 values (16 bytes, two groups of 16) a step.
    for (uint c = lane; c < K / 32u; c += 32u) {{
        const uint4 w = qr[c];
        const int e[8] = {{e2m1x4(w.x), e2m1x4(w.x >> 16u), e2m1x4(w.y), e2m1x4(w.y >> 16u),
                          e2m1x4(w.z), e2m1x4(w.z >> 16u), e2m1x4(w.w), e2m1x4(w.w >> 16u)}};
        const float s0 = fp8_e4m3(sr[2u * c]), s1 = fp8_e4m3(sr[2u * c + 1u]);
        #pragma unroll
        for (uint i = 0; i < M; ++i) {{
            // 32 int16 inputs: four uint4, two for each group of 16.
            const uint4* xr = reinterpret_cast<const uint4*>(xq + (size_t)i * K) + 4u * c;
            const float* sx = xs + (size_t)i * (K / 16u);
            const uint4 a0 = xr[0], a1 = xr[1], b0 = xr[2], b1 = xr[3];
            // __dp2a_lo / __dp2a_hi: the two int16 of the first operand
            // against bytes 0-1 / 2-3 of the second's four int8.
            int d0 = 0, d1 = 0;
            d0 = __dp2a_lo((int)a0.x, e[0], d0); d0 = __dp2a_hi((int)a0.y, e[0], d0);
            d0 = __dp2a_lo((int)a0.z, e[1], d0); d0 = __dp2a_hi((int)a0.w, e[1], d0);
            d0 = __dp2a_lo((int)a1.x, e[2], d0); d0 = __dp2a_hi((int)a1.y, e[2], d0);
            d0 = __dp2a_lo((int)a1.z, e[3], d0); d0 = __dp2a_hi((int)a1.w, e[3], d0);
            d1 = __dp2a_lo((int)b0.x, e[4], d1); d1 = __dp2a_hi((int)b0.y, e[4], d1);
            d1 = __dp2a_lo((int)b0.z, e[5], d1); d1 = __dp2a_hi((int)b0.w, e[5], d1);
            d1 = __dp2a_lo((int)b1.x, e[6], d1); d1 = __dp2a_hi((int)b1.y, e[6], d1);
            d1 = __dp2a_lo((int)b1.z, e[7], d1); d1 = __dp2a_hi((int)b1.w, e[7], d1);
            acc[i] += (float)d0 * (s0 * sx[2u * c]) + (float)d1 * (s1 * sx[2u * c + 1u]);
        }}
    }}
    #pragma unroll
    for (uint i = 0; i < M; ++i) {{
        float v = acc[i];
        for (uint d = 16u; d > 0u; d >>= 1u) v += __shfl_down_sync(0xffffffffu, v, d);
        // Halved: the table holds twice each E2M1 value.
        if (lane == 0u) y[i * N + row] = v * gs[row] * 0.5f{radd};
    }}
}}
"#,
        includes = Cuda.includes(),
        fp4 = Cuda.fp4_preamble(),
    );
    let mut writes = vec![false; 5];
    if residual {
        writes.push(false);
    }
    writes.push(true);
    Ok(Lowered {
        entry,
        source,
        grid: n.div_ceil(WARPS),
        grid2: 1,
        threads: THREADS,
        threadgroup_bytes: 0,
        arena_bytes: 0,
        scratch_bytes: 0,
        barriers: 0,
        writes,
    })
}
