//! The two small kernels that let a prefill pass run on more rows than the
//! prompt has -- a prompt padded up to a size the load compiled, in one pass
//! over the weights, instead of cut into several -- for CUDA.
//!
//! Every row-wise stage is indifferent to extra rows: the GEMMs, the norms,
//! the attention (causal, so a padded row sees only earlier rows and no real
//! row sees it) and the KV cache (a padded row writes a position the next
//! real token overwrites). The gated-delta layers are the exception: they
//! carry state across rows, so padded rows must leave it unchanged.
//!
//! - **The delta state.** A padded row's gate inputs are made a no-op: the
//!   decay `exp(amp * softplus(a + dt_bias))` is 1 and the write strength
//!   `sigmoid(b)` is 0 when `a` and `b` are very negative. [`ab_rows`]
//!   writes `NOOP` for every row at or past the real count, in the same
//!   kernel that computes the real rows' projections -- which is also why it
//!   exists in this form: the two dense `a`/`b` projections were 96 launches
//!   a prefill at 714 us each, one instance per (output, token), every
//!   instance re-reading its weight row.
//! - **The convolution state** is the last `K - 1` input rows. After a
//!   padded pass those are padded rows; [`conv_restore`] copies the last
//!   real ones from the projection's output.
//!
//! Both read the real row count from a one-word buffer, so one compiled
//! pass serves every real length up to its size.

use crate::dialect::{Cuda, Dialect};
use crate::program::Lowered;

/// A gate input so negative that the decay is exactly 1 and the write
/// strength underflows to 0 in f32.
pub const NOOP: f32 = -50.0;

/// Tokens a block, outputs a block, inputs a step, tokens a thread.
const TB: usize = 16;
const OB: usize = 32;
const KT: usize = 32;
const TPT: usize = TB / 4;

/// Whether [`ab_rows`] takes this shape: `n_in` a whole number of K steps,
/// and the two projections' rows together a whole number of output tiles.
pub fn ab_fits(tokens: usize, n_in: usize, n_out: usize) -> bool {
    tokens > 0 && n_in.is_multiple_of(KT) && (2 * n_out).is_multiple_of(OB)
}

/// `ya = x wa^T` and `yb = x wb^T` for `tokens` rows of `x` (`[tokens, n_in]`,
/// f16 or f32), `wa` and `wb` `[n_out, n_in]` f32, outputs `[tokens, n_out]`
/// f32 -- with every row at or past the count in `sc[0]` set to [`NOOP`].
///
/// Parameters, in order: `x`, `wa`, `wb`, `ya`, `yb`, `sc`.
pub fn ab_rows(tokens: usize, n_in: usize, n_out: usize, x_half: bool) -> Result<Lowered, String> {
    if !ab_fits(tokens, n_in, n_out) {
        return Err(format!(
            "ab_rows: {tokens} tokens, {n_in} inputs (whole steps of {KT}), \
             2 x {n_out} outputs (whole tiles of {OB})"
        ));
    }
    let entry = format!(
        "ab_rows_{tokens}_{n_out}x{n_in}{}",
        if x_half { "_xh" } else { "" }
    );
    let xt = if x_half { "__half" } else { "float" };
    let source = AB_SOURCE
        .replace("$ENTRY", &entry)
        .replace("$INCLUDES", &Cuda.includes())
        .replace("$XT", xt)
        .replace("$TOKENS", &tokens.to_string())
        .replace("$NIN", &n_in.to_string())
        .replace("$NOUT", &n_out.to_string())
        .replace("$NOOP", &format!("{NOOP:?}"))
        .replace("$TPT", &TPT.to_string())
        .replace("$TB", &TB.to_string())
        .replace("$OB", &OB.to_string())
        .replace("$KT", &KT.to_string());
    Ok(Lowered {
        entry,
        source,
        grid: (2 * n_out) / OB,
        grid2: tokens.div_ceil(TB),
        threads: 128,
        threadgroup_bytes: 4 * (TB * (KT + 1) + KT * (OB + 1)),
        arena_bytes: 0,
        scratch_bytes: 0,
        barriers: 2,
        // x, wa, wb, ya, yb, sc
        writes: vec![false, false, false, true, true, false],
    })
}

const AB_SOURCE: &str = r#"// Generated by lex-msl::pad. Hand-scheduled, not lowered from a program.
// kernel : $ENTRY
// launch : (2 x $NOUT / $OB) x ($TOKENS / $TB) blocks x 128 threads
$INCLUDES
extern "C" __global__ void $ENTRY(
    const $XT* __restrict__ x,
    const float* __restrict__ wa,
    const float* __restrict__ wb,
    float* __restrict__ ya,
    float* __restrict__ yb,
    const unsigned int* __restrict__ sc)
{
    const unsigned int T = $TOKENSu, K = $NINu, N = $NOUTu;
    const unsigned int o0 = blockIdx.x * $OBu, t0 = blockIdx.y * $TBu;
    const unsigned int tid = threadIdx.x, ol = tid % $OBu, tg = tid / $OBu;
    const unsigned int nreal = sc[0];
    __shared__ float xs[$TB][$KT + 1];
    __shared__ float ws[$KT][$OB + 1];
    float acc[$TPT];
    for (int i = 0; i < $TPT; ++i) acc[i] = 0.0f;
    for (unsigned int k0 = 0; k0 < K; k0 += $KTu) {
        for (unsigned int e = tid; e < $TBu * $KTu; e += 128u) {
            const unsigned int r = e / $KTu, c = e % $KTu, tok = t0 + r;
            xs[r][c] = tok < T ? (float)x[(size_t)tok * K + k0 + c] : 0.0f;
        }
        for (unsigned int e = tid; e < $OBu * $KTu; e += 128u) {
            const unsigned int o = e / $KTu, c = e % $KTu, og = o0 + o;
            const float* w = og < N ? wa : wb;
            ws[c][o] = w[(size_t)(og < N ? og : og - N) * K + k0 + c];
        }
        __syncthreads();
        #pragma unroll
        for (unsigned int c = 0; c < $KTu; ++c) {
            const float w = ws[c][ol];
            #pragma unroll
            for (int i = 0; i < $TPT; ++i) acc[i] += w * xs[tg * $TPT + i][c];
        }
        __syncthreads();
    }
    const unsigned int og = o0 + ol;
    for (int i = 0; i < $TPT; ++i) {
        const unsigned int tok = t0 + tg * $TPT + i;
        if (tok >= T) continue;
        const float v = tok < nreal ? acc[i] : $NOOPf;
        if (og < N) ya[(size_t)tok * N + og] = v;
        else yb[(size_t)tok * N + (og - N)] = v;
    }
}
"#;

/// Threads a block of [`conv_restore`].
const RESTORE_THREADS: usize = 256;

/// `state[r][c] = qkv[nreal - k1 + r][c]` for the `k1` rows and `ch`
/// channels of a convolution's carried window, `nreal` being `sc[0]` (at
/// least `k1`). Parameters: `state` (`[k1, ch]` f32), `qkv` (`[tokens, ch]`
/// f32), `sc`.
pub fn conv_restore(tokens: usize, ch: usize, k1: usize) -> Result<Lowered, String> {
    if tokens < k1 || ch == 0 || k1 == 0 {
        return Err(format!(
            "conv_restore: {tokens} tokens, {ch} channels, window {k1}"
        ));
    }
    let entry = format!("conv_restore_{tokens}_{ch}x{k1}");
    let source = format!(
        r#"// Generated by lex-msl::pad. Hand-scheduled, not lowered from a program.
// kernel : {entry}
{includes}
extern "C" __global__ void {entry}(
    float* __restrict__ state,
    const float* __restrict__ qkv,
    const unsigned int* __restrict__ sc)
{{
    const unsigned int e = blockIdx.x * {threads}u + threadIdx.x;
    if (e >= {k1}u * {ch}u) return;
    const unsigned int r = e / {ch}u, c = e % {ch}u;
    state[e] = qkv[(size_t)(sc[0] - {k1}u + r) * {ch}u + c];
}}
"#,
        includes = Cuda.includes(),
        threads = RESTORE_THREADS,
    );
    Ok(Lowered {
        entry,
        source,
        grid: (k1 * ch).div_ceil(RESTORE_THREADS),
        grid2: 1,
        threads: RESTORE_THREADS,
        threadgroup_bytes: 0,
        arena_bytes: 0,
        scratch_bytes: 0,
        barriers: 0,
        // state, qkv, sc
        writes: vec![true, false, false],
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_noop_gate_inputs_are_a_noop_in_f32() {
        // decay = exp(amp * softplus(a + dt_bias)), amp = -exp(A_log) in
        // about [-20, 0], dt_bias in about [-10, 10]; strength = sigmoid(b).
        for amp in [-0.01f32, -1.0, -20.0] {
            for dt in [-10.0f32, 0.0, 10.0] {
                let sp = (1.0 + (NOOP + dt).exp()).ln();
                assert_eq!((amp * sp).exp(), 1.0, "amp {amp} dt {dt}");
            }
        }
        assert!(1.0 / (1.0 + (-NOOP).exp()) < 1e-20);
    }

    #[test]
    fn shapes_are_checked_and_sources_name_their_parameters() {
        assert!(ab_fits(512, 5120, 48) && ab_fits(16, 5120, 48));
        assert!(!ab_fits(512, 5100, 48) && !ab_fits(512, 5120, 47));
        let l = ab_rows(512, 5120, 48, true).unwrap();
        assert_eq!((l.grid, l.grid2, l.threads), (3, 32, 128));
        assert!(l.source.contains("const __half* __restrict__ x"));
        assert!(!l.source.contains('$'), "an unreplaced placeholder");
        let l = ab_rows(16, 5120, 48, false).unwrap();
        assert!(l.source.contains("const float* __restrict__ x"));
        let r = conv_restore(512, 10240, 3).unwrap();
        assert_eq!(r.grid, (3 * 10240usize).div_ceil(256));
        assert!(conv_restore(2, 10240, 3).is_err());
    }
}
