//! Metal Shading Language text emitter.
//!
//! The backend emits MSL source rather than going through MLIR/SPIR-V. That is
//! a deliberate v1 choice: `simdgroup_matrix` and the threadgroup intrinsics
//! stay first-class with no translation loss, Xcode's GPU capture can still map
//! the shader back to something readable, and the whole dependency is a string
//! builder.
//!
//! Emission is a pure function of `(Kernel, Plan)` and produces no I/O, which
//! is what lets the golden tests run on any host — including a Linux CI box
//! with no Metal toolchain anywhere near it.

use std::fmt::Write as _;

use tile_ir::{DType, Kernel, Op, Plan, Target};

/// Emit a standalone MSL translation unit containing one kernel.
pub fn emit(kernel: &Kernel, plan: &Plan, target: &Target) -> String {
    let mut s = String::with_capacity(2048);
    emit_header(&mut s, kernel, plan, target);
    s.push_str("#include <metal_stdlib>\nusing namespace metal;\n\n");
    match kernel.op {
        Op::Copy { dtype, .. } => emit_copy(&mut s, &kernel.name, dtype, plan),
        Op::RmsNorm {
            dtype, cols, eps, ..
        } => emit_rmsnorm(&mut s, &kernel.name, dtype, cols, eps, plan),
    }
    s
}

/// A provenance comment. Every emitted kernel carries the facts needed to tell
/// whether the *plan* or the *emitter* is at fault when a number disappoints —
/// the cheapest possible version of the source-map requirement.
fn emit_header(s: &mut String, kernel: &Kernel, plan: &Plan, target: &Target) {
    let _ = writeln!(s, "// Generated by tile-msl. Do not edit by hand.");
    let _ = writeln!(s, "// kernel : {}", kernel.name);
    let _ = writeln!(s, "// op     : {:?}", kernel.op);
    let _ = writeln!(
        s,
        "// target : {} (simd {}, threadgroup budget {} B)",
        target.name, target.simd_width, target.max_threadgroup_bytes
    );
    let _ = writeln!(
        s,
        "// launch : {} threadgroups x {} threads, vec{}",
        plan.launch.threadgroups[0], plan.threads_per_tg, plan.vec_width
    );
    let _ = writeln!(
        s,
        "// tg mem : {} B of {} B",
        plan.threadgroup_bytes, target.max_threadgroup_bytes
    );
    s.push('\n');
}

fn emit_copy(s: &mut String, name: &str, dtype: DType, plan: &Plan) {
    let v4 = dtype.msl_vec4();
    let _ = write!(
        s,
        "kernel void {name}(
    device const {v4} *x [[buffer(0)]],
    device {v4} *y [[buffer(1)]],
    uint gid [[thread_position_in_grid]])
{{
    // The grid is rounded up to a whole threadgroup, so the tail must be
    // masked. A planner that guaranteed exact division could drop this.
    if (gid >= {lanes}u) {{ return; }}
    y[gid] = x[gid];
}}
",
        lanes = plan.vec_lanes,
    );
}

fn emit_rmsnorm(s: &mut String, name: &str, dtype: DType, cols: usize, eps: f32, plan: &Plan) {
    let v4 = dtype.msl_vec4();
    let lanes = plan.vec_lanes;
    let tg = plan.threads_per_tg;
    let sgs = plan.simdgroups_per_tg;
    let eps = fmt_f32(eps);

    let _ = write!(
        s,
        "kernel void {name}(
    device const {v4} *x [[buffer(0)]],
    device const {v4} *w [[buffer(1)]],
    device {v4} *y [[buffer(2)]],
    uint row  [[threadgroup_position_in_grid]],
    uint tid  [[thread_position_in_threadgroup]],
    uint lane [[thread_index_in_simdgroup]],
    uint sg   [[simdgroup_index_in_threadgroup]])
{{
    // One f32 partial per simdgroup: {tg_bytes} B, checked against the target
    // table at plan time rather than discovered at pipeline creation.
    threadgroup float partial[{sgs}];

    // One threadgroup owns one row, so the row base is uniform across it.
    // The cast to ulong matters: rows * cols overflows 32 bits well before it
    // exhausts the memory of a Mac Studio.
    device const {v4} *xr = x + (ulong)row * {lanes}u;
    device {v4} *yr = y + (ulong)row * {lanes}u;

    // Pass 1: sum of squares, accumulated in f32 whatever the storage type.
    float acc = 0.0f;
    for (uint i = tid; i < {lanes}u; i += {tg}u) {{
        float4 v = float4(xr[i]);
        acc += dot(v, v);
    }}

    // Two-stage reduction: within each simdgroup, then across simdgroups.
    // `sg` is uniform within a simdgroup, so the guarded simd_sum below is
    // entered by all 32 lanes together.
    acc = simd_sum(acc);
    if (lane == 0u) {{ partial[sg] = acc; }}
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (sg == 0u) {{
        float v = (lane < {sgs}u) ? partial[lane] : 0.0f;
        v = simd_sum(v);
        if (lane == 0u) {{ partial[0] = v; }}
    }}
    threadgroup_barrier(mem_flags::mem_threadgroup);

    const float scale = rsqrt(partial[0] / {cols}.0f + {eps});

    // Pass 2: re-read the row, scale, write out. That re-read is the reason
    // this kernel cannot reach the copy ceiling once a row misses cache.
    // Staging the row in threadgroup memory instead is a scheduling decision,
    // not an algorithm change -- which is exactly the split P3 makes explicit.
    for (uint i = tid; i < {lanes}u; i += {tg}u) {{
        yr[i] = {v4}(float4(xr[i]) * float4(w[i]) * scale);
    }}
}}
",
        tg_bytes = plan.threadgroup_bytes,
    );
}

/// Format an f32 as a C float literal that round-trips.
fn fmt_f32(v: f32) -> String {
    let mut s = format!("{v:?}");
    if !s.contains(['.', 'e', 'E']) {
        s.push_str(".0");
    }
    s.push('f');
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use tile_ir::plan;

    fn apple() -> Target {
        Target::apple_m_series()
    }

    #[test]
    fn float_literals_round_trip() {
        assert_eq!(fmt_f32(1e-5), "1e-5f");
        assert_eq!(fmt_f32(0.0), "0.0f");
        assert_eq!(fmt_f32(1.0), "1.0f");
    }

    #[test]
    fn braces_balance_in_every_kernel() {
        let t = apple();
        for k in [
            Kernel::copy(DType::F32, 4096),
            Kernel::copy(DType::F16, 4096),
            Kernel::rmsnorm(DType::F32, 8, 4096, 1e-5),
            Kernel::rmsnorm(DType::F16, 8, 4096, 1e-5),
        ] {
            let p = plan(&k, &t).unwrap();
            let src = emit(&k, &p, &t);
            let opens = src.chars().filter(|c| *c == '{').count();
            let closes = src.chars().filter(|c| *c == '}').count();
            assert_eq!(opens, closes, "unbalanced braces in {}", k.name);
            assert!(src.contains(&format!("kernel void {}(", k.name)));
        }
    }

    #[test]
    fn scratch_array_matches_the_plan() {
        let t = apple();
        let k = Kernel::rmsnorm(DType::F32, 8, 4096, 1e-5);
        let p = plan(&k, &t).unwrap();
        let src = emit(&k, &p, &t);
        assert!(src.contains(&format!(
            "threadgroup float partial[{}];",
            p.simdgroups_per_tg
        )));
        assert_eq!(p.simdgroups_per_tg * 4, p.threadgroup_bytes);
    }

    #[test]
    fn dtype_reaches_every_buffer_declaration() {
        let t = apple();
        let k = Kernel::rmsnorm(DType::F16, 8, 4096, 1e-5);
        let p = plan(&k, &t).unwrap();
        let src = emit(&k, &p, &t);
        for decl in [
            "device const half4 *x",
            "device const half4 *w",
            "device half4 *y",
            "device const half4 *xr",
            "device half4 *yr",
        ] {
            assert!(src.contains(decl), "missing `{decl}` in:\n{src}");
        }
        // The accumulator stays f32 even when storage is f16 -- that is the
        // numeric contract the reference implementation is written against.
        assert!(src.contains("float acc = 0.0f;"));
        assert!(
            !src.contains("float4 *"),
            "an f32 buffer leaked into an f16 kernel"
        );
    }

    #[test]
    fn stride_loop_matches_the_launch() {
        let t = apple();
        let k = Kernel::rmsnorm(DType::F32, 8, 4096, 1e-5);
        let p = plan(&k, &t).unwrap();
        let src = emit(&k, &p, &t);
        assert!(src.contains(&format!("i += {}u", p.threads_per_tg)));
        assert!(src.contains(&format!("i < {}u", p.vec_lanes)));
    }
}
