//! Lower a checked `tile-front` program to one MSL kernel.
//!
//! P2's contract is *correct at any speed*, so this is the simplest lowering
//! that is right for every program the checker accepts:
//!
//! - One threadgroup per grid instance. `T` threads, chosen by the caller.
//! - **Register tiles** are distributed cyclically: thread `t` owns flat
//!   elements `t, t + T, t + 2T, …`, held in a `PER = ceil(n / T)` array.
//!   Elementwise ops between equal-sized tiles never leave the thread.
//! - An operand some *other* thread owns — a matmul input, a row-broadcast
//!   vector, a row reduction's input — is **staged** through a threadgroup
//!   scratch area first.
//! - **Threadgroup tiles** get a fixed offset in a static arena per allocation
//!   site, and travel through copies, waits and loop carries as pointers. That
//!   is what makes a rotated double buffer a pointer swap.
//! - Metal has no async copy engine, so `copy_async` is a cooperative copy at
//!   issue time and `wait` is a barrier. That is only sound because linearity
//!   proves nothing still owns the destination buffer.
//! - Barriers are conservative: before every threadgroup write, and between
//!   staging and use. Deriving the minimal set from the effect graph is P3.
//!
//! Everything is computed in f32 and narrowed only where a tile's dtype says
//! so, which is exactly what the interpreter does — so the GPU and the
//! interpreter differ only in `exp`'s last bits.

use std::collections::HashMap;
use std::fmt::Write as _;

use tile_front::ir::{Arg, BinOp, Block, IdxExpr, Op, Program, Reduce, Stmt, TileTy, Var, View};
use tile_ir::{DType, Space, Target};

/// A lowered kernel and everything needed to launch it.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Lowered {
    pub entry: String,
    pub source: String,
    /// Threadgroups to launch: one per grid instance.
    pub grid: usize,
    pub threads: usize,
    /// Arena (threadgroup tiles) plus staging scratch.
    pub threadgroup_bytes: usize,
    pub arena_bytes: usize,
    pub scratch_bytes: usize,
    /// Barrier sites in the source (not dynamic count).
    pub barriers: usize,
}

/// Where a value lives in the generated code.
#[derive(Clone, Debug)]
enum Loc {
    /// A distributed register tile: `expr[k]` is this thread's k-th element.
    Reg(String, TileTy),
    /// An array of register tiles: `name[i][k]`.
    RegArr(String, TileTy, usize),
    /// A threadgroup tile: `name[e]` is flat element `e`.
    Tg(String, TileTy),
    Index(String),
}

/// How an op reads one operand at a flat element index.
enum Access {
    /// This thread's own element: `expr[k]`.
    Local(String),
    /// Any element, from threadgroup memory: `base[..]`.
    Shared(String),
}

struct Gen<'a> {
    prog: &'a Program,
    threads: usize,
    body: String,
    depth: usize,
    locs: HashMap<Var, Loc>,
    arena: usize,
    scratch: usize,
    barriers: usize,
}

/// Lower `prog` (which must already pass `tile_front::check` for `target`)
/// with `threads` threads per threadgroup.
pub fn lower(prog: &Program, target: &Target, threads: usize) -> Result<Lowered, String> {
    if threads == 0
        || !threads.is_multiple_of(target.simd_width)
        || threads > target.max_threads_per_threadgroup
    {
        return Err(format!(
            "{threads} threads is not a whole number of simdgroups within {}'s limit of {}",
            target.name, target.max_threads_per_threadgroup
        ));
    }
    let mut g = Gen {
        prog,
        threads,
        body: String::new(),
        depth: 1,
        locs: HashMap::new(),
        arena: 0,
        scratch: 0,
        barriers: 0,
    };
    if let Some(pid) = prog.pid {
        g.locs.insert(pid, Loc::Index("gid".into()));
    }
    g.block(&prog.body)?;

    let entry = ident(&prog.name);
    let scratch_bytes = g.scratch * 4;
    let arena_bytes = g.arena;
    let threadgroup_bytes = arena_bytes + scratch_bytes;
    if threadgroup_bytes > target.max_threadgroup_bytes {
        return Err(format!(
            "lowering needs {threadgroup_bytes} B of threadgroup memory ({arena_bytes} B of tiles \
             + {scratch_bytes} B of staging scratch); {} allows {}",
            target.name, target.max_threadgroup_bytes
        ));
    }

    let mut s = String::new();
    let _ = writeln!(
        s,
        "// Generated by tile-msl from a tile-front program. Do not edit by hand."
    );
    let _ = writeln!(s, "// kernel : {}", prog.name);
    let _ = writeln!(s, "// target : {}", target.name);
    let _ = writeln!(
        s,
        "// launch : {} threadgroups x {threads} threads",
        prog.grid
    );
    let _ = writeln!(
        s,
        "// tg mem : {arena_bytes} B tiles + {scratch_bytes} B scratch of {} B",
        target.max_threadgroup_bytes
    );
    s.push_str("\n#include <metal_stdlib>\nusing namespace metal;\n\n");
    let _ = writeln!(s, "kernel void {entry}(");
    for (i, p) in prog.params.iter().enumerate() {
        let cv = if p.writable { "" } else { "const " };
        let _ = writeln!(
            s,
            "    device {cv}{}* {} [[buffer({i})]],",
            p.dtype.msl_scalar(),
            param_ident(i, &p.name)
        );
    }
    s.push_str("    uint tid [[thread_index_in_threadgroup]],\n");
    s.push_str("    uint gid [[threadgroup_position_in_grid]])\n{\n");
    if arena_bytes > 0 {
        let _ = writeln!(
            s,
            "    threadgroup float4 arena4[{}];\n    threadgroup uchar* arena = (threadgroup uchar*)arena4;",
            arena_bytes.div_ceil(16)
        );
    }
    if g.scratch > 0 {
        let _ = writeln!(s, "    threadgroup float scratch[{}];", g.scratch);
    }
    s.push_str(&g.body);
    s.push_str("}\n");

    Ok(Lowered {
        entry,
        source: s,
        grid: prog.grid,
        threads,
        threadgroup_bytes,
        arena_bytes,
        scratch_bytes,
        barriers: g.barriers,
    })
}

fn ident(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

fn param_ident(i: usize, name: &str) -> String {
    format!("p{i}_{}", ident(name))
}

fn v(var: Var) -> String {
    format!("v{}", var.0)
}

/// The storage name a location reads from.
fn storage(l: &Loc) -> String {
    match l {
        Loc::Reg(n, _) | Loc::RegArr(n, _, _) | Loc::Tg(n, _) | Loc::Index(n) => n.clone(),
    }
}

fn lit(x: f32) -> String {
    if x == f32::INFINITY {
        "INFINITY".into()
    } else if x == f32::NEG_INFINITY {
        "(-INFINITY)".into()
    } else {
        format!("{x:?}f")
    }
}

impl Gen<'_> {
    fn line(&mut self, text: &str) {
        for _ in 0..self.depth {
            self.body.push_str("    ");
        }
        self.body.push_str(text);
        self.body.push('\n');
    }

    fn barrier(&mut self) {
        self.barriers += 1;
        self.line("threadgroup_barrier(mem_flags::mem_threadgroup);");
    }

    fn per(&self, n: usize) -> usize {
        n.div_ceil(self.threads)
    }

    fn loc(&self, x: Var) -> Result<Loc, String> {
        self.locs
            .get(&x)
            .cloned()
            .ok_or_else(|| format!("`{}` has no storage", self.prog.name_of(x)))
    }

    fn idx(&self, e: &IdxExpr) -> Result<String, String> {
        let mut parts = vec![e.constant.to_string()];
        for &(x, c) in &e.terms {
            let Loc::Index(name) = self.loc(x)? else {
                return Err("index expression over a non-index".into());
            };
            parts.push(format!("{c} * {name}"));
        }
        Ok(format!("(uint)({})", parts.join(" + ")))
    }

    /// Device address of flat element `e` of `view`, as MSL.
    fn addr(&self, view: &View, e: &str) -> Result<String, String> {
        let dims = &self.prog.params[view.param].shape;
        let r = dims.len();
        let mut terms = vec![];
        for d in 0..r {
            let inner: usize = view.shape[d + 1..].iter().product();
            let stride: usize = dims[d + 1..].iter().product();
            let coord = format!("(({e}) / {inner}u % {}u)", view.shape[d]);
            terms.push(format!(
                "({} + {coord}) * {stride}u",
                self.idx(&view.offset[d])?
            ));
        }
        Ok(format!(
            "{}[{}]",
            param_ident(view.param, &self.prog.params[view.param].name),
            terms.join(" + ")
        ))
    }

    /// `for each element this thread owns: body(k, e)`.
    fn owned(&mut self, n: usize, body: &[String]) {
        let (per, t) = (self.per(n), self.threads);
        self.line(&format!("for (uint k = 0; k < {per}u; ++k) {{"));
        self.depth += 1;
        self.line(&format!("const uint e = k * {t}u + tid;"));
        self.line(&format!("if (e < {n}u) {{"));
        self.depth += 1;
        for b in body {
            self.line(b);
        }
        self.depth -= 1;
        self.line("}");
        self.depth -= 1;
        self.line("}");
    }

    /// `for every element, cooperatively: body(e)`.
    fn every(&mut self, n: usize, body: &str) {
        let t = self.threads;
        self.line(&format!("for (uint e = tid; e < {n}u; e += {t}u) {{"));
        self.depth += 1;
        self.line(body);
        self.depth -= 1;
        self.line("}");
    }

    fn declare_reg(&mut self, x: Var, ty: &TileTy) -> String {
        let name = v(x);
        let per = self.per(ty.elems());
        self.line(&format!("{} {name}[{per}];", ty.dtype.msl_scalar()));
        self.locs.insert(x, Loc::Reg(name.clone(), ty.clone()));
        name
    }

    fn declare_tg(&mut self, x: Var, ty: &TileTy) -> String {
        let name = v(x);
        let off = self.arena.next_multiple_of(16);
        self.arena = off + ty.bytes();
        let st = ty.dtype.msl_scalar();
        self.line(&format!(
            "threadgroup {st}* {name} = (threadgroup {st}*)(arena + {off});"
        ));
        self.locs.insert(x, Loc::Tg(name.clone(), ty.clone()));
        name
    }

    /// Resolve operands for an op whose output has `out_elems` elements.
    /// `local[i]` says operand i is read at the output's own element index.
    /// Register operands that are not local are staged into scratch.
    fn operands(
        &mut self,
        args: &[Arg],
        local: &[bool],
        out_elems: usize,
    ) -> Result<Vec<(Access, TileTy)>, String> {
        let mut out = vec![];
        let mut stage = vec![];
        let mut off = 0;
        for (a, &loc_ok) in args.iter().zip(local) {
            let (expr, ty, reg) = match *a {
                Arg::Move(x) | Arg::Borrow(x) => match self.loc(x)? {
                    Loc::Reg(n, t) => (n, t, true),
                    Loc::Tg(n, t) => (n, t, false),
                    _ => return Err("operand is not a tile".into()),
                },
                Arg::BorrowElem(arr, i) => {
                    let (Loc::RegArr(n, t, _), Loc::Index(iname)) = (self.loc(arr)?, self.loc(i)?)
                    else {
                        return Err("unsupported array element operand".into());
                    };
                    (format!("{n}[{iname}]"), t, true)
                }
                Arg::BorrowPart(..) => {
                    return Err("pipe shares have no Metal lowering".into());
                }
            };
            if !reg {
                out.push((Access::Shared(expr), ty));
            } else if loc_ok && ty.elems() == out_elems {
                out.push((Access::Local(expr), ty));
            } else {
                let base = format!("(scratch + {off})");
                stage.push((expr, ty.elems(), off));
                off += ty.elems();
                out.push((Access::Shared(base), ty));
            }
        }
        if !stage.is_empty() {
            self.scratch = self.scratch.max(off);
            // Nobody may still be reading the scratch from the previous op.
            self.barrier();
            for (expr, n, o) in stage {
                self.owned(n, &[format!("scratch[{o} + e] = float({expr}[k]);")]);
            }
            self.barrier();
        }
        Ok(out)
    }

    fn read(a: &Access, at: &str) -> String {
        match a {
            Access::Local(x) => format!("float({x}[k])"),
            Access::Shared(x) => format!("float({x}[{at}])"),
        }
    }

    fn block(&mut self, b: &Block) -> Result<(), String> {
        for s in &b.stmts {
            self.stmt(s)?;
        }
        Ok(())
    }

    fn stmt(&mut self, s: &Stmt) -> Result<(), String> {
        match s {
            Stmt::Let { dst, op } => self.op(*dst, op),
            Stmt::For {
                index,
                start,
                end,
                init,
                params,
                body,
                results,
            } => {
                for (&i, &p) in init.iter().zip(params) {
                    let src = self.loc(i)?;
                    self.bind_copy(p, &src)?;
                }
                let iname = v(*index);
                self.line(&format!(
                    "for (uint {iname} = {start}u; {iname} < {end}u; ++{iname}) {{"
                ));
                self.depth += 1;
                self.locs.insert(*index, Loc::Index(iname));
                self.block(body)?;
                // Carries are assigned in parallel: a rotated double buffer
                // yields pointers that *are* other carries' storage, so a
                // sequential assignment would read one it just overwrote.
                let mut moves = vec![];
                for (&y, &p) in body.yields.iter().zip(params) {
                    moves.push((self.loc(p)?, self.loc(y)?));
                }
                let names: Vec<String> = moves.iter().map(|(d, _)| storage(d)).collect();
                let mut staged = vec![];
                for (i, (dst, src)) in moves.iter().enumerate() {
                    let aliases_other = names
                        .iter()
                        .enumerate()
                        .any(|(j, n)| j != i && *n == storage(src));
                    match (dst, src) {
                        (Loc::Tg(_, t), Loc::Tg(sn, _)) if aliases_other => {
                            let tmp = format!("{}_next", storage(dst));
                            self.line(&format!(
                                "threadgroup {}* {tmp} = {sn};",
                                t.dtype.msl_scalar()
                            ));
                            staged.push((dst.clone(), Loc::Tg(tmp, t.clone())));
                        }
                        _ if aliases_other => {
                            return Err(
                                "a loop that permutes register carries is not lowered yet".into()
                            );
                        }
                        _ => staged.push((dst.clone(), src.clone())),
                    }
                }
                for (dst, src) in staged {
                    self.assign(&dst, &src)?;
                }
                self.depth -= 1;
                self.line("}");
                for (&r, &p) in results.iter().zip(params) {
                    let l = self.loc(p)?;
                    self.locs.insert(r, l);
                }
                Ok(())
            }
            Stmt::MapEach {
                index,
                arrays,
                params,
                body,
                results,
            } => {
                let mut n = 0;
                let mut ins = vec![];
                for &a in arrays {
                    let Loc::RegArr(name, t, len) = self.loc(a)? else {
                        return Err("map_each over a non-register array is not lowered".into());
                    };
                    n = len;
                    ins.push((name, t));
                }
                // Result arrays live outside the loop, so they are declared
                // before the body that determines their element type. They
                // take the input arrays' element types, and the yields are
                // checked against that below.
                let mut outs = vec![];
                for (k, &r) in results.iter().enumerate() {
                    let t = ins
                        .get(k)
                        .map(|x| x.1.clone())
                        .ok_or("map_each yields more arrays than it walks")?;
                    let name = v(r);
                    let per = self.per(t.elems());
                    self.line(&format!("{} {name}[{n}][{per}];", t.dtype.msl_scalar()));
                    outs.push((r, name, t));
                }
                let iname = v(*index);
                self.line(&format!(
                    "for (uint {iname} = 0; {iname} < {n}u; ++{iname}) {{"
                ));
                self.depth += 1;
                self.locs.insert(*index, Loc::Index(iname.clone()));
                for (&p, (name, t)) in params.iter().zip(&ins) {
                    let pname = v(p);
                    self.line(&format!(
                        "thread {}* {pname} = {name}[{iname}];",
                        t.dtype.msl_scalar()
                    ));
                    self.locs.insert(p, Loc::Reg(pname, t.clone()));
                }
                self.block(body)?;
                for (&y, (_, name, t)) in body.yields.iter().zip(&outs) {
                    let src = self.loc(y)?;
                    if !matches!(&src, Loc::Reg(_, st) if st == t) {
                        return Err("map_each that changes element type is not lowered yet".into());
                    }
                    let dst = Loc::Reg(format!("{name}[{iname}]"), t.clone());
                    self.assign(&dst, &src)?;
                }
                self.depth -= 1;
                self.line("}");
                for (r, name, t) in outs {
                    self.locs.insert(r, Loc::RegArr(name, t, n));
                }
                Ok(())
            }
            Stmt::Specialize { .. } => {
                Err("warp-specialised roles have no Metal lowering (no split barriers)".into())
            }
        }
    }

    /// Declare fresh storage for `p` holding a copy of `src`.
    fn bind_copy(&mut self, p: Var, src: &Loc) -> Result<(), String> {
        match src {
            Loc::Reg(_, t) => {
                let t = t.clone();
                self.declare_reg(p, &t);
            }
            Loc::RegArr(_, t, n) => {
                let name = v(p);
                let per = self.per(t.elems());
                self.line(&format!("{} {name}[{n}][{per}];", t.dtype.msl_scalar()));
                self.locs.insert(p, Loc::RegArr(name, t.clone(), *n));
            }
            Loc::Tg(_, t) => {
                let name = v(p);
                self.line(&format!("threadgroup {}* {name};", t.dtype.msl_scalar()));
                self.locs.insert(p, Loc::Tg(name, t.clone()));
            }
            Loc::Index(_) => return Err("an index cannot be carried".into()),
        }
        let dst = self.loc(p)?;
        self.assign(&dst, src)
    }

    /// `dst = src`, by value for registers and by pointer for threadgroup.
    fn assign(&mut self, dst: &Loc, src: &Loc) -> Result<(), String> {
        match (dst, src) {
            (Loc::Reg(d, t), Loc::Reg(s, _)) => {
                if d != s {
                    let per = self.per(t.elems());
                    self.line(&format!(
                        "for (uint k = 0; k < {per}u; ++k) {d}[k] = {s}[k];"
                    ));
                }
            }
            (Loc::RegArr(d, t, n), Loc::RegArr(s, _, _)) => {
                if d != s {
                    let per = self.per(t.elems());
                    self.line(&format!(
                        "for (uint i = 0; i < {n}u; ++i) for (uint k = 0; k < {per}u; ++k) \
                         {d}[i][k] = {s}[i][k];"
                    ));
                }
            }
            (Loc::Tg(d, _), Loc::Tg(s, _)) => {
                if d != s {
                    self.line(&format!("{d} = {s};"));
                }
            }
            _ => return Err("carry changes storage class".into()),
        }
        Ok(())
    }

    fn op(&mut self, dst: Option<Var>, op: &Op) -> Result<(), String> {
        let reg = |dt: DType, shape: &[usize]| TileTy::new(dt, shape, Space::Reg);
        match op {
            Op::Alloc(t) => {
                let x = dst.ok_or("alloc without a result")?;
                match t.space {
                    Space::Threadgroup => {
                        self.declare_tg(x, t);
                    }
                    _ => {
                        self.declare_reg(x, t);
                    }
                }
            }
            Op::Fill(t, val) => {
                let x = dst.ok_or("fill without a result")?;
                let st = t.dtype.msl_scalar();
                match t.space {
                    Space::Threadgroup => {
                        let name = self.declare_tg(x, t);
                        self.barrier();
                        self.every(t.elems(), &format!("{name}[e] = {st}({});", lit(*val)));
                        self.barrier();
                    }
                    _ => {
                        let name = self.declare_reg(x, t);
                        self.owned(t.elems(), &[format!("{name}[k] = {st}({});", lit(*val))]);
                    }
                }
            }
            Op::Load(view, t) => {
                let x = dst.ok_or("load without a result")?;
                let st = t.dtype.msl_scalar();
                let src = self.addr(view, "e")?;
                match t.space {
                    Space::Threadgroup => {
                        let name = self.declare_tg(x, t);
                        self.barrier();
                        self.every(t.elems(), &format!("{name}[e] = {st}({src});"));
                        self.barrier();
                    }
                    _ => {
                        let name = self.declare_reg(x, t);
                        self.owned(t.elems(), &[format!("{name}[k] = {st}({src});")]);
                    }
                }
            }
            Op::CopyAsync(view, buf) => {
                let x = dst.ok_or("copy without a result")?;
                let Loc::Tg(name, t) = self.loc(*buf)? else {
                    return Err("copy destination is not threadgroup memory".into());
                };
                let src = self.addr(view, "e")?;
                // The destination was last read as some earlier tile: every
                // thread must be done with it before anyone overwrites it.
                self.barrier();
                self.every(t.elems(), &format!("{name}[e] = {src};"));
                self.locs.insert(x, Loc::Tg(name, t));
            }
            Op::Wait(f) => {
                let x = dst.ok_or("wait without a result")?;
                let l = self.loc(*f)?;
                self.barrier();
                self.locs.insert(x, l);
            }
            Op::Store(a, view) => {
                let dt = self.prog.params[view.param].dtype.msl_scalar();
                let n = view.shape.iter().product();
                let ops = self.operands(&[*a], &[true], n)?;
                let target = self.addr(view, "e")?;
                match &ops[0].0 {
                    Access::Local(_) => {
                        let val = Self::read(&ops[0].0, "e");
                        self.owned(n, &[format!("{target} = {dt}({val});")]);
                    }
                    Access::Shared(_) => {
                        let val = Self::read(&ops[0].0, "e");
                        self.barrier();
                        self.every(n, &format!("{target} = {dt}({val});"));
                    }
                }
            }
            Op::Drop(_) => {}
            Op::Dup(a) | Op::Exp(a) | Op::Scale(a, _) | Op::Convert(a, _) => {
                let x = dst.ok_or("op without a result")?;
                let ty = self.arg_ty(*a)?;
                let n = ty.elems();
                let ops = self.operands(&[*a], &[true], n)?;
                let src = Self::read(&ops[0].0, "e");
                let (dt, expr) = match op {
                    Op::Dup(_) => (ty.dtype, src),
                    Op::Exp(_) => (ty.dtype, format!("precise::exp({src})")),
                    Op::Scale(_, f) => (ty.dtype, format!("{src} * {}", lit(*f))),
                    Op::Convert(_, d) => (*d, src),
                    _ => unreachable!(),
                };
                let name = self.declare_reg(x, &reg(dt, &ty.shape));
                self.owned(n, &[format!("{name}[k] = {}({expr});", dt.msl_scalar())]);
            }
            Op::Binary(bop, a, b) => {
                let x = dst.ok_or("op without a result")?;
                let (ta, tb) = (self.arg_ty(*a)?, self.arg_ty(*b)?);
                let n = ta.elems();
                let bcast = ta.shape != tb.shape;
                let ops = self.operands(&[*a, *b], &[true, !bcast], n)?;
                let cols = if bcast { ta.shape[1] } else { 1 };
                let lhs = Self::read(&ops[0].0, "e");
                let rhs = Self::read(&ops[1].0, &format!("e / {cols}u"));
                let expr = match bop {
                    BinOp::Add => format!("{lhs} + {rhs}"),
                    BinOp::Sub => format!("{lhs} - {rhs}"),
                    BinOp::Mul => format!("{lhs} * {rhs}"),
                    BinOp::Div => format!("{lhs} / {rhs}"),
                    BinOp::Max => format!("max({lhs}, {rhs})"),
                };
                let dt = ta.dtype;
                let name = self.declare_reg(x, &reg(dt, &ta.shape));
                self.owned(n, &[format!("{name}[k] = {}({expr});", dt.msl_scalar())]);
            }
            Op::MatMulNT(a, b, acc) | Op::MatMul(a, b, acc) => {
                let x = dst.ok_or("matmul without a result")?;
                let (ta, tb) = (self.arg_ty(*a)?, self.arg_ty(*b)?);
                let nt = matches!(op, Op::MatMulNT(..));
                let (m, kd) = (ta.shape[0], ta.shape[1]);
                let n = if nt { tb.shape[0] } else { tb.shape[1] };
                let ops = self.operands(&[*a, *b], &[false, false], m * n)?;
                let av = Self::read(&ops[0].0, &format!("i * {kd}u + p"));
                let bv = if nt {
                    Self::read(&ops[1].0, &format!("j * {kd}u + p"))
                } else {
                    Self::read(&ops[1].0, &format!("p * {n}u + j"))
                };
                let name = self.declare_reg(x, &reg(*acc, &[m, n]));
                self.owned(
                    m * n,
                    &[
                        format!("const uint i = e / {n}u, j = e % {n}u;"),
                        "float s = 0.0f;".into(),
                        format!("for (uint p = 0; p < {kd}u; ++p) s += {av} * {bv};"),
                        format!("{name}[k] = {}(s);", acc.msl_scalar()),
                    ],
                );
            }
            Op::RowReduce(r, a) => {
                let x = dst.ok_or("reduce without a result")?;
                let ta = self.arg_ty(*a)?;
                let (m, n) = (ta.shape[0], ta.shape[1]);
                let ops = self.operands(&[*a], &[false], m)?;
                let val = Self::read(&ops[0].0, &format!("e * {n}u + j"));
                let (init, step) = match r {
                    Reduce::Max => ("(-INFINITY)", format!("s = max(s, {val});")),
                    Reduce::Sum => ("0.0f", format!("s += {val};")),
                };
                let dt = ta.dtype;
                let name = self.declare_reg(x, &reg(dt, &[m]));
                self.owned(
                    m,
                    &[
                        format!("float s = {init};"),
                        format!("for (uint j = 0; j < {n}u; ++j) {step}"),
                        format!("{name}[k] = {}(s);", dt.msl_scalar()),
                    ],
                );
            }
            Op::MakeArray(vs) => {
                let x = dst.ok_or("array without a result")?;
                let mut elems = vec![];
                for &e in vs {
                    let Loc::Reg(n, t) = self.loc(e)? else {
                        return Err("arrays of threadgroup tiles are not lowered".into());
                    };
                    elems.push((n, t));
                }
                let t = elems[0].1.clone();
                let name = v(x);
                let per = self.per(t.elems());
                self.line(&format!(
                    "{} {name}[{}][{per}];",
                    t.dtype.msl_scalar(),
                    elems.len()
                ));
                for (i, (n, _)) in elems.iter().enumerate() {
                    self.line(&format!(
                        "for (uint k = 0; k < {per}u; ++k) {name}[{i}][k] = {n}[k];"
                    ));
                }
                self.locs.insert(x, Loc::RegArr(name, t, vs.len()));
            }
            Op::Acquire(_) | Op::Commit(..) | Op::Receive(_) | Op::Release(..) => {
                return Err("pipes have no Metal lowering (no split barriers)".into());
            }
        }
        Ok(())
    }

    fn arg_ty(&self, a: Arg) -> Result<TileTy, String> {
        Ok(match a {
            Arg::Move(x) | Arg::Borrow(x) => match self.loc(x)? {
                Loc::Reg(_, t) | Loc::Tg(_, t) => t,
                _ => return Err("operand is not a tile".into()),
            },
            Arg::BorrowElem(arr, _) => match self.loc(arr)? {
                Loc::RegArr(_, t, _) => t,
                _ => return Err("operand is not an array".into()),
            },
            Arg::BorrowPart(..) => return Err("pipe shares have no Metal lowering".into()),
        })
    }
}
