// Generated by lex-cuda. Do not edit by hand.
// kernel : copy_f16
// op     : Copy { dtype: F16, n: 4096 }
// target : nvidia-ada (sm_89, warp 32, shared budget 101376 B)
// launch : 4 blocks x 256 threads, vec4
// shared : 0 B of 101376 B

#include <cuda_fp16.h>

struct __align__(8) half4 { __half x, y, z, w; };

__device__ __forceinline__ float4 to_f4(float4 v) { return v; }
__device__ __forceinline__ float4 to_f4(half4 v) {
    return make_float4(__half2float(v.x), __half2float(v.y),
                       __half2float(v.z), __half2float(v.w));
}
__device__ __forceinline__ void from_f4(float4 s, float4 &d) { d = s; }
__device__ __forceinline__ void from_f4(float4 s, half4 &d) {
    d.x = __float2half(s.x); d.y = __float2half(s.y);
    d.z = __float2half(s.z); d.w = __float2half(s.w);
}

__device__ __forceinline__ float dot4(float4 a, float4 b) {
    return a.x * b.x + a.y * b.y + a.z * b.z + a.w * b.w;
}
__device__ __forceinline__ float4 mul4(float4 a, float4 b) {
    return make_float4(a.x * b.x, a.y * b.y, a.z * b.z, a.w * b.w);
}
__device__ __forceinline__ float4 scale4(float4 a, float s) {
    return make_float4(a.x * s, a.y * s, a.z * s, a.w * s);
}

__device__ __forceinline__ float warp_sum(float v) {
#pragma unroll
    for (int o = 16; o > 0; o >>= 1) v += __shfl_xor_sync(0xffffffffu, v, o);
    return v;
}

extern "C" __global__ void copy_f16(
    const half4 *__restrict__ x,
    half4 *__restrict__ y)
{
    const unsigned gid = blockIdx.x * blockDim.x + threadIdx.x;
    // The grid is rounded up to a whole block, so the tail must be masked.
    // A planner that guaranteed exact division could drop this.
    if (gid >= 1024u) { return; }
    y[gid] = x[gid];
}
