// Generated by lex-cuda. Do not edit by hand.
// kernel : rmsnorm_f32
// op     : RmsNorm { dtype: F32, rows: 8, cols: 4096, eps: 1e-5 }
// target : nvidia-ada (sm_89, warp 32, shared budget 101376 B)
// launch : 8 blocks x 256 threads, vec4
// shared : 32 B of 101376 B

#include <cuda_fp16.h>

struct __align__(8) half4 { __half x, y, z, w; };

__device__ __forceinline__ float4 to_f4(float4 v) { return v; }
__device__ __forceinline__ float4 to_f4(half4 v) {
    return make_float4(__half2float(v.x), __half2float(v.y),
                       __half2float(v.z), __half2float(v.w));
}
__device__ __forceinline__ void from_f4(float4 s, float4 &d) { d = s; }
__device__ __forceinline__ void from_f4(float4 s, half4 &d) {
    d.x = __float2half(s.x); d.y = __float2half(s.y);
    d.z = __float2half(s.z); d.w = __float2half(s.w);
}

__device__ __forceinline__ float dot4(float4 a, float4 b) {
    return a.x * b.x + a.y * b.y + a.z * b.z + a.w * b.w;
}
__device__ __forceinline__ float4 mul4(float4 a, float4 b) {
    return make_float4(a.x * b.x, a.y * b.y, a.z * b.z, a.w * b.w);
}
__device__ __forceinline__ float4 scale4(float4 a, float s) {
    return make_float4(a.x * s, a.y * s, a.z * s, a.w * s);
}

__device__ __forceinline__ float warp_sum(float v) {
#pragma unroll
    for (int o = 16; o > 0; o >>= 1) v += __shfl_xor_sync(0xffffffffu, v, o);
    return v;
}

extern "C" __global__ void rmsnorm_f32(
    const float4 *__restrict__ x,
    const float4 *__restrict__ w,
    float4 *__restrict__ y)
{
    const unsigned row  = blockIdx.x;
    const unsigned tid  = threadIdx.x;
    const unsigned lane = threadIdx.x & 31u;
    const unsigned sg   = threadIdx.x >> 5;

    // One f32 partial per warp: 32 B, checked against the target
    // table at plan time rather than discovered at launch.
    __shared__ float partial[8];

    // One block owns one row, so the row base is uniform across it. The cast
    // to size_t matters: rows * cols overflows 32 bits well before it
    // exhausts the memory of an L4.
    const float4 *xr = x + (size_t)row * 1024u;
    float4 *yr = y + (size_t)row * 1024u;

    // Pass 1: sum of squares, accumulated in f32 whatever the storage type.
    float acc = 0.0f;
    for (unsigned i = tid; i < 1024u; i += 256u) {
        float4 v = to_f4(xr[i]);
        acc += dot4(v, v);
    }

    // Two-stage reduction: within each warp, then across warps. `sg` is
    // uniform within a warp, so every lane reaches the same warp_sum.
    acc = warp_sum(acc);
    if (lane == 0u) { partial[sg] = acc; }
    __syncthreads();
    if (sg == 0u) {
        float v = (lane < 8u) ? partial[lane] : 0.0f;
        v = warp_sum(v);
        if (lane == 0u) { partial[0] = v; }
    }
    __syncthreads();

    const float scale = rsqrtf(partial[0] / 4096.0f + 1e-5f);

    // Pass 2: re-read the row, scale, write out. That re-read is the reason
    // this kernel cannot reach the copy ceiling once a row misses cache.
    // Staging the row in shared memory instead is a scheduling decision, not
    // an algorithm change -- which is exactly the split P3 makes explicit.
    for (unsigned i = tid; i < 1024u; i += 256u) {
        float4 v = mul4(to_f4(xr[i]), to_f4(w[i]));
        from_f4(scale4(v, scale), yr[i]);
    }
}
