[workspace]
resolver = "3"
members = [
    "crates/lex-ir",
    "crates/lex-front",
    "crates/lex-msl",
    "crates/lex-cuda",
    "crates/lex-metal",
    "crates/lex-bench",
    "crates/lex-rt",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "EUPL-1.2"
repository = "https://github.com/alpibrusl/lex-gpu"

[workspace.dependencies]
lex-ir = { path = "crates/lex-ir" }
lex-front = { path = "crates/lex-front" }
lex-msl = { path = "crates/lex-msl" }
lex-cuda = { path = "crates/lex-cuda" }
lex-metal = { path = "crates/lex-metal" }
lex-rt = { path = "crates/lex-rt" }
half = "2"

[profile.release]
debug = true
