[workspace]
resolver = "3"
members = [
    "crates/tile-ir",
    "crates/tile-front",
    "crates/tile-msl",
    "crates/tile-metal",
    "crates/tile-bench",
    "crates/tile-rt",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "EUPL-1.2"
repository = "https://github.com/alpibrusl/lex-gpu"

[workspace.dependencies]
tile-ir = { path = "crates/tile-ir" }
tile-front = { path = "crates/tile-front" }
tile-msl = { path = "crates/tile-msl" }
tile-metal = { path = "crates/tile-metal" }
tile-rt = { path = "crates/tile-rt" }
half = "2"

[profile.release]
debug = true
