// Generated by tile-msl. Do not edit by hand.
// kernel : copy_f16
// op     : Copy { dtype: F16, n: 4096 }
// target : apple-m-series (simd 32, threadgroup budget 32768 B)
// launch : 4 threadgroups x 256 threads, vec4
// tg mem : 0 B of 32768 B

#include <metal_stdlib>
using namespace metal;

kernel void copy_f16(
    device const half4 *x [[buffer(0)]],
    device half4 *y [[buffer(1)]],
    uint gid [[thread_position_in_grid]])
{
    // The grid is rounded up to a whole threadgroup, so the tail must be
    // masked. A planner that guaranteed exact division could drop this.
    if (gid >= 1024u) { return; }
    y[gid] = x[gid];
}
