// Generated by tile-msl from a tile-front program. Do not edit by hand.
// kernel : flash_decode_f16_bq4_bk16_s2
// target : apple-m-series
// launch : 2 threadgroups x 128 threads
// tg mem : 8192 B tiles + 1280 B scratch of 32768 B

#include <metal_stdlib>
using namespace metal;

kernel void flash_decode_f16_bq4_bk16_s2(
    device const half* p0_q [[buffer(0)]],
    device const half* p1_k [[buffer(1)]],
    device const half* p2_v [[buffer(2)]],
    device float* p3_o [[buffer(3)]],
    uint tid [[thread_index_in_threadgroup]],
    uint gid [[threadgroup_position_in_grid]])
{
    threadgroup float4 arena4[512];
    threadgroup uchar* arena = (threadgroup uchar*)arena4;
    threadgroup float scratch[320];
    half v1_m[2];
    for (uint k = 0; k < 2u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 256u) {
            v1_m[k] = half(half(p0_q[((uint)(0 + 8 * gid) + (((e)) / 64u % 4u)) * 64u + ((uint)(0) + (((e)) / 1u % 64u)) * 1u]));
        }
    }
    half v2_m[2];
    for (uint k = 0; k < 2u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 256u) {
            v2_m[k] = half(half(p0_q[((uint)(4 + 8 * gid) + (((e)) / 64u % 4u)) * 64u + ((uint)(0) + (((e)) / 1u % 64u)) * 1u]));
        }
    }
    half v3[2][2];
    for (uint k = 0; k < 2u; ++k) v3[0][k] = v1_m[k];
    for (uint k = 0; k < 2u; ++k) v3[1][k] = v2_m[k];
    float v4[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 4u) {
            v4[k] = float((-INFINITY));
        }
    }
    float v5[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 4u) {
            v5[k] = float((-INFINITY));
        }
    }
    float v6[2][1];
    for (uint k = 0; k < 1u; ++k) v6[0][k] = v4[k];
    for (uint k = 0; k < 1u; ++k) v6[1][k] = v5[k];
    float v7[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 4u) {
            v7[k] = float(0.0f);
        }
    }
    float v8[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 4u) {
            v8[k] = float(0.0f);
        }
    }
    float v9[2][1];
    for (uint k = 0; k < 1u; ++k) v9[0][k] = v7[k];
    for (uint k = 0; k < 1u; ++k) v9[1][k] = v8[k];
    float v10[2];
    for (uint k = 0; k < 2u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 256u) {
            v10[k] = float(0.0f);
        }
    }
    float v11[2];
    for (uint k = 0; k < 2u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 256u) {
            v11[k] = float(0.0f);
        }
    }
    float v12[2][2];
    for (uint k = 0; k < 2u; ++k) v12[0][k] = v10[k];
    for (uint k = 0; k < 2u; ++k) v12[1][k] = v11[k];
    threadgroup half* v13 = (threadgroup half*)(arena + 0);
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint e = tid; e < 1024u; e += 128u) {
        v13[e] = p1_k[((uint)(0 + 64 * gid) + ((e) / 64u % 16u)) * 64u + ((uint)(0) + ((e) / 1u % 64u)) * 1u];
    }
    threadgroup half* v15 = (threadgroup half*)(arena + 2048);
    threadgroup half* v16 = (threadgroup half*)(arena + 4096);
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint e = tid; e < 1024u; e += 128u) {
        v16[e] = p2_v[((uint)(0 + 64 * gid) + ((e) / 64u % 16u)) * 64u + ((uint)(0) + ((e) / 1u % 64u)) * 1u];
    }
    threadgroup half* v18 = (threadgroup half*)(arena + 6144);
    float v20[2][1];
    for (uint i = 0; i < 2u; ++i) for (uint k = 0; k < 1u; ++k) v20[i][k] = v6[i][k];
    float v21[2][1];
    for (uint i = 0; i < 2u; ++i) for (uint k = 0; k < 1u; ++k) v21[i][k] = v9[i][k];
    float v22[2][2];
    for (uint i = 0; i < 2u; ++i) for (uint k = 0; k < 2u; ++k) v22[i][k] = v12[i][k];
    threadgroup half* v23;
    v23 = v13;
    threadgroup half* v24;
    v24 = v15;
    threadgroup half* v25;
    v25 = v16;
    threadgroup half* v26;
    v26 = v18;
    for (uint v19 = 0u; v19 < 3u; ++v19) {
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint e = tid; e < 1024u; e += 128u) {
            v24[e] = p1_k[((uint)(16 + 16 * v19 + 64 * gid) + ((e) / 64u % 16u)) * 64u + ((uint)(0) + ((e) / 1u % 64u)) * 1u];
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint e = tid; e < 1024u; e += 128u) {
            v26[e] = p2_v[((uint)(16 + 16 * v19 + 64 * gid) + ((e) / 64u % 16u)) * 64u + ((uint)(0) + ((e) / 1u % 64u)) * 1u];
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        threadgroup_barrier(mem_flags::mem_threadgroup);
        float v49[2][1];
        float v50[2][1];
        float v51[2][2];
        for (uint v31 = 0; v31 < 2u; ++v31) {
            thread float* v32 = v20[v31];
            thread float* v33 = v21[v31];
            thread float* v34 = v22[v31];
            threadgroup_barrier(mem_flags::mem_threadgroup);
            for (uint k = 0; k < 2u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 256u) {
                    scratch[0 + e] = float(v3[v31][k]);
                }
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            {
                const uint o = tid / 2u, lane = tid % 2u;
                float s = 0.0f;
                if (o < 64u) {
                    const uint i = o / 16u, j = o % 16u;
                    for (uint p0 = lane * 8u; p0 < 64u; p0 += 16u) {
                        for (uint u = 0; u < 8u; ++u) { const uint p = p0 + u; s += float((scratch + 0)[i * 64u + p]) * float(v23[j * 64u + p]); }
                    }
                }
                for (uint d = 1u; d > 0; d /= 2) s += simd_shuffle_down(s, d);
                if (o < 64u && lane == 0) scratch[256 + o] = s;
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            float v35[1];
            for (uint k = 0; k < 1u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 64u) {
                    v35[k] = float(scratch[256 + e]);
                }
            }
            float v36[1];
            for (uint k = 0; k < 1u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 64u) {
                    v36[k] = float(float(v35[k]) * 0.125f);
                }
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            for (uint k = 0; k < 1u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 64u) {
                    scratch[0 + e] = float(v36[k]);
                }
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            {
                const uint o = tid / 16u, lane = tid % 16u;
                float s = (-INFINITY);
                if (o < 4u) for (uint j = lane; j < 16u; j += 16u) s = max(s, float((scratch + 0)[o * 16u + j]));
                for (uint d = 8u; d > 0; d /= 2) s = max(s, simd_shuffle_down(s, d));
                if (o < 4u && lane % 32u == 0) scratch[64 + o * 1u + lane / 32u] = s;
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            float v37[1];
            for (uint k = 0; k < 1u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 4u) {
                    float s = (-INFINITY);
                    for (uint q = 0; q < 1u; ++q) s = max(s, scratch[64 + e * 1u + q]);
                    v37[k] = float(s);
                }
            }
            float v38[1];
            for (uint k = 0; k < 1u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 4u) {
                    v38[k] = float(max(float(v32[k]), float(v37[k])));
                }
            }
            float v39[1];
            for (uint k = 0; k < 1u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 4u) {
                    v39[k] = float(float(v32[k]) - float(v38[k]));
                }
            }
            float v40[1];
            for (uint k = 0; k < 1u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 4u) {
                    v40[k] = float(precise::exp(float(v39[k])));
                }
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            for (uint k = 0; k < 1u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 4u) {
                    scratch[0 + e] = float(v38[k]);
                }
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            float v41[1];
            for (uint k = 0; k < 1u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 64u) {
                    v41[k] = float(float(v36[k]) - float((scratch + 0)[e / 16u]));
                }
            }
            float v42[1];
            for (uint k = 0; k < 1u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 64u) {
                    v42[k] = float(precise::exp(float(v41[k])));
                }
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            for (uint k = 0; k < 1u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 64u) {
                    scratch[0 + e] = float(v42[k]);
                }
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            {
                const uint o = tid / 16u, lane = tid % 16u;
                float s = 0.0f;
                if (o < 4u) for (uint j = lane; j < 16u; j += 16u) s = s + float((scratch + 0)[o * 16u + j]);
                for (uint d = 8u; d > 0; d /= 2) s = s + simd_shuffle_down(s, d);
                if (o < 4u && lane % 32u == 0) scratch[64 + o * 1u + lane / 32u] = s;
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            float v43[1];
            for (uint k = 0; k < 1u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 4u) {
                    float s = 0.0f;
                    for (uint q = 0; q < 1u; ++q) s = s + scratch[64 + e * 1u + q];
                    v43[k] = float(s);
                }
            }
            float v44[1];
            for (uint k = 0; k < 1u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 4u) {
                    v44[k] = float(float(v33[k]) * float(v40[k]));
                }
            }
            float v45[1];
            for (uint k = 0; k < 1u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 4u) {
                    v45[k] = float(float(v44[k]) + float(v43[k]));
                }
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            for (uint k = 0; k < 1u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 64u) {
                    scratch[0 + e] = float(v42[k]);
                }
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            float v46[2];
            for (uint k = 0; k < 2u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 256u) {
                    const uint i = e / 64u, j = e % 64u;
                    float s = 0.0f;
                    for (uint p = 0; p < 16u; ++p) s += float((scratch + 0)[i * 16u + p]) * float(v25[p * 64u + j]);
                    v46[k] = float(s);
                }
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            for (uint k = 0; k < 1u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 4u) {
                    scratch[0 + e] = float(v40[k]);
                }
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            float v47[2];
            for (uint k = 0; k < 2u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 256u) {
                    v47[k] = float(float(v34[k]) * float((scratch + 0)[e / 64u]));
                }
            }
            float v48[2];
            for (uint k = 0; k < 2u; ++k) {
                const uint e = k * 128u + tid;
                if (e < 256u) {
                    v48[k] = float(float(v47[k]) + float(v46[k]));
                }
            }
            for (uint k = 0; k < 1u; ++k) v49[v31][k] = v38[k];
            for (uint k = 0; k < 1u; ++k) v50[v31][k] = v45[k];
            for (uint k = 0; k < 2u; ++k) v51[v31][k] = v48[k];
        }
        threadgroup half* v23_next = v24;
        threadgroup half* v24_next = v23;
        threadgroup half* v25_next = v26;
        threadgroup half* v26_next = v25;
        for (uint i = 0; i < 2u; ++i) for (uint k = 0; k < 1u; ++k) v20[i][k] = v49[i][k];
        for (uint i = 0; i < 2u; ++i) for (uint k = 0; k < 1u; ++k) v21[i][k] = v50[i][k];
        for (uint i = 0; i < 2u; ++i) for (uint k = 0; k < 2u; ++k) v22[i][k] = v51[i][k];
        v23 = v23_next;
        v24 = v24_next;
        v25 = v25_next;
        v26 = v26_next;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v79[2][1];
    float v80[2][1];
    float v81[2][2];
    for (uint v61 = 0; v61 < 2u; ++v61) {
        thread float* v62 = v20[v61];
        thread float* v63 = v21[v61];
        thread float* v64 = v22[v61];
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint k = 0; k < 2u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 256u) {
                scratch[0 + e] = float(v3[v61][k]);
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        {
            const uint o = tid / 2u, lane = tid % 2u;
            float s = 0.0f;
            if (o < 64u) {
                const uint i = o / 16u, j = o % 16u;
                for (uint p0 = lane * 8u; p0 < 64u; p0 += 16u) {
                    for (uint u = 0; u < 8u; ++u) { const uint p = p0 + u; s += float((scratch + 0)[i * 64u + p]) * float(v23[j * 64u + p]); }
                }
            }
            for (uint d = 1u; d > 0; d /= 2) s += simd_shuffle_down(s, d);
            if (o < 64u && lane == 0) scratch[256 + o] = s;
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        float v65[1];
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 64u) {
                v65[k] = float(scratch[256 + e]);
            }
        }
        float v66[1];
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 64u) {
                v66[k] = float(float(v65[k]) * 0.125f);
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 64u) {
                scratch[0 + e] = float(v66[k]);
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        {
            const uint o = tid / 16u, lane = tid % 16u;
            float s = (-INFINITY);
            if (o < 4u) for (uint j = lane; j < 16u; j += 16u) s = max(s, float((scratch + 0)[o * 16u + j]));
            for (uint d = 8u; d > 0; d /= 2) s = max(s, simd_shuffle_down(s, d));
            if (o < 4u && lane % 32u == 0) scratch[64 + o * 1u + lane / 32u] = s;
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        float v67[1];
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 4u) {
                float s = (-INFINITY);
                for (uint q = 0; q < 1u; ++q) s = max(s, scratch[64 + e * 1u + q]);
                v67[k] = float(s);
            }
        }
        float v68[1];
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 4u) {
                v68[k] = float(max(float(v62[k]), float(v67[k])));
            }
        }
        float v69[1];
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 4u) {
                v69[k] = float(float(v62[k]) - float(v68[k]));
            }
        }
        float v70[1];
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 4u) {
                v70[k] = float(precise::exp(float(v69[k])));
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 4u) {
                scratch[0 + e] = float(v68[k]);
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        float v71[1];
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 64u) {
                v71[k] = float(float(v66[k]) - float((scratch + 0)[e / 16u]));
            }
        }
        float v72[1];
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 64u) {
                v72[k] = float(precise::exp(float(v71[k])));
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 64u) {
                scratch[0 + e] = float(v72[k]);
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        {
            const uint o = tid / 16u, lane = tid % 16u;
            float s = 0.0f;
            if (o < 4u) for (uint j = lane; j < 16u; j += 16u) s = s + float((scratch + 0)[o * 16u + j]);
            for (uint d = 8u; d > 0; d /= 2) s = s + simd_shuffle_down(s, d);
            if (o < 4u && lane % 32u == 0) scratch[64 + o * 1u + lane / 32u] = s;
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        float v73[1];
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 4u) {
                float s = 0.0f;
                for (uint q = 0; q < 1u; ++q) s = s + scratch[64 + e * 1u + q];
                v73[k] = float(s);
            }
        }
        float v74[1];
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 4u) {
                v74[k] = float(float(v63[k]) * float(v70[k]));
            }
        }
        float v75[1];
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 4u) {
                v75[k] = float(float(v74[k]) + float(v73[k]));
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 64u) {
                scratch[0 + e] = float(v72[k]);
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        float v76[2];
        for (uint k = 0; k < 2u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 256u) {
                const uint i = e / 64u, j = e % 64u;
                float s = 0.0f;
                for (uint p = 0; p < 16u; ++p) s += float((scratch + 0)[i * 16u + p]) * float(v25[p * 64u + j]);
                v76[k] = float(s);
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 4u) {
                scratch[0 + e] = float(v70[k]);
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        float v77[2];
        for (uint k = 0; k < 2u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 256u) {
                v77[k] = float(float(v64[k]) * float((scratch + 0)[e / 64u]));
            }
        }
        float v78[2];
        for (uint k = 0; k < 2u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 256u) {
                v78[k] = float(float(v77[k]) + float(v76[k]));
            }
        }
        for (uint k = 0; k < 1u; ++k) v79[v61][k] = v68[k];
        for (uint k = 0; k < 1u; ++k) v80[v61][k] = v75[k];
        for (uint k = 0; k < 2u; ++k) v81[v61][k] = v78[k];
    }
    for (uint v82 = 0; v82 < 2u; ++v82) {
        thread float* v83 = v79[v82];
        thread float* v84 = v80[v82];
        thread float* v85 = v81[v82];
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 4u) {
                scratch[0 + e] = float(v84[k]);
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        float v86[2];
        for (uint k = 0; k < 2u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 256u) {
                v86[k] = float(float(v85[k]) / float((scratch + 0)[e / 64u]));
            }
        }
        for (uint k = 0; k < 2u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 256u) {
                p3_o[((uint)(0 + 4 * v82 + 8 * gid) + ((e) / 64u % 4u)) * 64u + ((uint)(0) + ((e) / 1u % 64u)) * 1u] = float(float(v86[k]));
            }
        }
    }
}
