//! CUDA C text emitter for the lex IR.
//!
//! The second backend, and the first test of the claim the whole design
//! rests on: that one typed program lowers to more than one target without
//! per-target kernel rewrites. Until this existed, that was an argument.
//!
//! It emits CUDA C rather than PTX for the same reason `lex-msl` emits MSL
//! rather than going through MLIR: the intrinsics that matter stay
//! first-class, `nsight` can map the source back, and the dependency is a
//! string builder. Emission is a pure function of `(Kernel, Plan, Target)`
//! and does no I/O, so the golden tests run anywhere — including a Mac with
//! no CUDA toolkit within reach.
//!
//! `scripts/cuda_check.sh` takes it one step further and compiles the output
//! with `nvcc` and `ptxas` in a container. Neither needs a GPU, so the only
//! thing left for a real device is whether it *runs*.
//!
//! ## What differs from Metal, and why it is not cosmetic
//!
//! The two backends emit the same algorithm and disagree about the machine:
//!
//! - **Vector types.** CUDA has `float4` but no `half4`, so one is defined in
//!   the preamble. The 8-byte alignment is load-bearing: without it `nvcc`
//!   issues four 2-byte loads where Metal issues one 8-byte load.
//! - **Reductions.** Metal's `simd_sum` returns the total to every lane.
//!   `__shfl_down_sync` leaves it only in lane 0, so this uses
//!   `__shfl_xor_sync`, which is a butterfly and broadcasts — matching the
//!   MSL semantics exactly rather than approximately.
//! - **Threadgroup budget.** Ada opts into 99 KiB of shared memory against
//!   Hopper's 227 and Apple's 32. A schedule that fits one may not fit
//!   another, which is what the target table is for.

// Only on Linux: macOS has no libcuda to link against, and gating the
// module rather than the calls is what lets the emitter and every golden
// test build on a Mac.
#[cfg(target_os = "linux")]
pub mod device;

use std::fmt::Write as _;

use lex_ir::{DType, Kernel, Op, Plan, Target};

/// 4-wide vector spelling in CUDA C. Only `half4` is ours; CUDA already has
/// `float4` and `char4`.
///
/// Deliberately *not* on `DType` next to `msl_vec4`. Target spellings belong
/// to the backend that speaks them, and the IR knowing about one backend is
/// a wart worth not doubling.
const fn vec4(d: DType) -> &'static str {
    match d {
        DType::F16 => "half4",
        DType::F32 => "float4",
        DType::I8 => "char4",
    }
}

/// The `-arch` a target assembles for, which `scripts/cuda_check.sh` and
/// `nvcc` both want.
pub const fn arch(target: &Target) -> &'static str {
    // `match` on &str is not const, so compare the pointer-free way.
    if matches!(target.name.as_bytes(), b"nvidia-hopper") {
        "sm_90"
    } else {
        "sm_89"
    }
}

/// Emit a standalone CUDA translation unit containing one kernel.
pub fn emit(kernel: &Kernel, plan: &Plan, target: &Target) -> String {
    let mut s = String::with_capacity(2048);
    emit_header(&mut s, kernel, plan, target);
    s.push_str(PREAMBLE);
    match kernel.op {
        Op::Copy { dtype, .. } => emit_copy(&mut s, &kernel.name, dtype, plan),
        Op::RmsNorm {
            dtype, cols, eps, ..
        } => emit_rmsnorm(&mut s, &kernel.name, dtype, cols, eps, plan),
    }
    s
}

/// A provenance comment, as the MSL backend emits: enough to tell whether
/// the *plan* or the *emitter* is at fault when a number disappoints.
fn emit_header(s: &mut String, kernel: &Kernel, plan: &Plan, target: &Target) {
    let _ = writeln!(s, "// Generated by lex-cuda. Do not edit by hand.");
    let _ = writeln!(s, "// kernel : {}", kernel.name);
    let _ = writeln!(s, "// op     : {:?}", kernel.op);
    let _ = writeln!(
        s,
        "// target : {} ({}, warp {}, shared budget {} B)",
        target.name,
        arch(target),
        target.simd_width,
        target.max_threadgroup_bytes
    );
    let _ = writeln!(
        s,
        "// launch : {} blocks x {} threads, vec{}",
        plan.launch.threadgroups[0], plan.threads_per_tg, plan.vec_width
    );
    let _ = writeln!(
        s,
        "// shared : {} B of {} B",
        plan.threadgroup_bytes, target.max_threadgroup_bytes
    );
    s.push('\n');
}

/// What CUDA does not give us and Metal does.
const PREAMBLE: &str = concat!(
    "#include <cuda_fp16.h>\n\n",
    // CUDA has float4 but no half4. The alignment is the point: without it
    // nvcc issues four 2-byte loads where one 8-byte load would do.
    "struct __align__(8) half4 { __half x, y, z, w; };\n",
    "\n",
    "__device__ __forceinline__ float4 to_f4(float4 v) { return v; }\n",
    "__device__ __forceinline__ float4 to_f4(half4 v) {\n",
    "    return make_float4(__half2float(v.x), __half2float(v.y),\n",
    "                       __half2float(v.z), __half2float(v.w));\n",
    "}\n",
    "__device__ __forceinline__ void from_f4(float4 s, float4 &d) { d = s; }\n",
    "__device__ __forceinline__ void from_f4(float4 s, half4 &d) {\n",
    "    d.x = __float2half(s.x); d.y = __float2half(s.y);\n",
    "    d.z = __float2half(s.z); d.w = __float2half(s.w);\n",
    "}\n\n",
    "__device__ __forceinline__ float dot4(float4 a, float4 b) {\n",
    "    return a.x * b.x + a.y * b.y + a.z * b.z + a.w * b.w;\n",
    "}\n",
    "__device__ __forceinline__ float4 mul4(float4 a, float4 b) {\n",
    "    return make_float4(a.x * b.x, a.y * b.y, a.z * b.z, a.w * b.w);\n",
    "}\n",
    "__device__ __forceinline__ float4 scale4(float4 a, float s) {\n",
    "    return make_float4(a.x * s, a.y * s, a.z * s, a.w * s);\n",
    "}\n\n",
    // Metal's simd_sum returns the total to every lane. __shfl_down_sync
    // leaves it only in lane 0; the xor butterfly broadcasts, so this
    // matches the MSL semantics rather than approximating them.
    "__device__ __forceinline__ float warp_sum(float v) {\n",
    "#pragma unroll\n",
    "    for (int o = 16; o > 0; o >>= 1) v += __shfl_xor_sync(0xffffffffu, v, o);\n",
    "    return v;\n",
    "}\n\n"
);

fn emit_copy(s: &mut String, name: &str, dtype: DType, plan: &Plan) {
    let v4 = vec4(dtype);
    let _ = write!(
        s,
        "extern \"C\" __global__ void {name}(
    const {v4} *__restrict__ x,
    {v4} *__restrict__ y)
{{
    const unsigned gid = blockIdx.x * blockDim.x + threadIdx.x;
    // The grid is rounded up to a whole block, so the tail must be masked.
    // A planner that guaranteed exact division could drop this.
    if (gid >= {lanes}u) {{ return; }}
    y[gid] = x[gid];
}}
",
        lanes = plan.vec_lanes,
    );
}

fn emit_rmsnorm(s: &mut String, name: &str, dtype: DType, cols: usize, eps: f32, plan: &Plan) {
    let v4 = vec4(dtype);
    let lanes = plan.vec_lanes;
    let tg = plan.threads_per_tg;
    let sgs = plan.simdgroups_per_tg;
    let eps = fmt_f32(eps);

    let _ = write!(
        s,
        "extern \"C\" __global__ void {name}(
    const {v4} *__restrict__ x,
    const {v4} *__restrict__ w,
    {v4} *__restrict__ y)
{{
    const unsigned row  = blockIdx.x;
    const unsigned tid  = threadIdx.x;
    const unsigned lane = threadIdx.x & 31u;
    const unsigned sg   = threadIdx.x >> 5;

    // One f32 partial per warp: {tg_bytes} B, checked against the target
    // table at plan time rather than discovered at launch.
    __shared__ float partial[{sgs}];

    // One block owns one row, so the row base is uniform across it. The cast
    // to size_t matters: rows * cols overflows 32 bits well before it
    // exhausts the memory of an L4.
    const {v4} *xr = x + (size_t)row * {lanes}u;
    {v4} *yr = y + (size_t)row * {lanes}u;

    // Pass 1: sum of squares, accumulated in f32 whatever the storage type.
    float acc = 0.0f;
    for (unsigned i = tid; i < {lanes}u; i += {tg}u) {{
        float4 v = to_f4(xr[i]);
        acc += dot4(v, v);
    }}

    // Two-stage reduction: within each warp, then across warps. `sg` is
    // uniform within a warp, so every lane reaches the same warp_sum.
    acc = warp_sum(acc);
    if (lane == 0u) {{ partial[sg] = acc; }}
    __syncthreads();
    if (sg == 0u) {{
        float v = (lane < {sgs}u) ? partial[lane] : 0.0f;
        v = warp_sum(v);
        if (lane == 0u) {{ partial[0] = v; }}
    }}
    __syncthreads();

    const float scale = rsqrtf(partial[0] / {cols}.0f + {eps});

    // Pass 2: re-read the row, scale, write out. That re-read is the reason
    // this kernel cannot reach the copy ceiling once a row misses cache.
    // Staging the row in shared memory instead is a scheduling decision, not
    // an algorithm change -- which is exactly the split P3 makes explicit.
    for (unsigned i = tid; i < {lanes}u; i += {tg}u) {{
        float4 v = mul4(to_f4(xr[i]), to_f4(w[i]));
        from_f4(scale4(v, scale), yr[i]);
    }}
}}
",
        tg_bytes = plan.threadgroup_bytes,
    );
}

/// Format an f32 as a C float literal that round-trips.
fn fmt_f32(v: f32) -> String {
    let mut s = format!("{v:?}");
    if !s.contains(['.', 'e', 'E']) {
        s.push_str(".0");
    }
    s.push('f');
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use lex_ir::plan;

    fn ada() -> Target {
        Target::nvidia_ada()
    }

    #[test]
    fn float_literals_round_trip() {
        assert_eq!(fmt_f32(1e-5), "1e-5f");
        assert_eq!(fmt_f32(0.0), "0.0f");
        assert_eq!(fmt_f32(1.0), "1.0f");
    }

    #[test]
    fn braces_balance_in_every_kernel() {
        let t = ada();
        for k in [
            Kernel::copy(DType::F32, 4096),
            Kernel::copy(DType::F16, 4096),
            Kernel::rmsnorm(DType::F32, 8, 4096, 1e-5),
            Kernel::rmsnorm(DType::F16, 8, 4096, 1e-5),
        ] {
            let p = plan(&k, &t).unwrap();
            let src = emit(&k, &p, &t);
            let opens = src.chars().filter(|c| *c == '{').count();
            let closes = src.chars().filter(|c| *c == '}').count();
            assert_eq!(opens, closes, "unbalanced braces in {}", k.name);
            assert!(src.contains(&format!("__global__ void {}(", k.name)));
        }
    }

    #[test]
    fn shared_array_matches_the_plan() {
        let t = ada();
        let k = Kernel::rmsnorm(DType::F32, 8, 4096, 1e-5);
        let p = plan(&k, &t).unwrap();
        let src = emit(&k, &p, &t);
        assert!(src.contains(&format!(
            "__shared__ float partial[{}];",
            p.simdgroups_per_tg
        )));
        assert_eq!(p.simdgroups_per_tg * 4, p.threadgroup_bytes);
    }

    #[test]
    fn dtype_reaches_every_buffer_declaration() {
        let t = ada();
        let k = Kernel::rmsnorm(DType::F16, 8, 4096, 1e-5);
        let p = plan(&k, &t).unwrap();
        let src = emit(&k, &p, &t);
        for decl in [
            "const half4 *__restrict__ x",
            "const half4 *__restrict__ w",
            "half4 *__restrict__ y",
            "const half4 *xr",
            "half4 *yr",
        ] {
            assert!(src.contains(decl), "missing `{decl}` in:\n{src}");
        }
        // The accumulator stays f32 even when storage is f16 -- the same
        // numeric contract the MSL backend and the interpreter are written
        // against. A backend that quietly accumulated in half would pass
        // every golden test and disagree with the reference.
        assert!(src.contains("float acc = 0.0f;"));
    }

    #[test]
    fn stride_loop_matches_the_launch() {
        let t = ada();
        let k = Kernel::rmsnorm(DType::F32, 8, 4096, 1e-5);
        let p = plan(&k, &t).unwrap();
        let src = emit(&k, &p, &t);
        assert!(src.contains(&format!("i += {}u", p.threads_per_tg)));
        assert!(src.contains(&format!("i < {}u", p.vec_lanes)));
    }

    /// The point of the exercise: the same kernel, planned for two targets,
    /// differs in the schedule and not in the algorithm.
    #[test]
    fn the_plan_follows_the_target() {
        let k = Kernel::rmsnorm(DType::F32, 8, 4096, 1e-5);
        let ada = Target::nvidia_ada();
        let hopper = Target::nvidia_hopper();
        for t in [&ada, &hopper] {
            let p = plan(&k, t).unwrap();
            let src = emit(&k, &p, t);
            assert!(src.contains(&format!("shared budget {} B", t.max_threadgroup_bytes)));
            assert!(src.contains("acc += dot4(v, v);"), "algorithm changed");
        }
        assert_eq!(arch(&ada), "sm_89");
        assert_eq!(arch(&hopper), "sm_90");
    }
}
