"""Generate the canonical-composition tables `tokenizer.rs` needs.

    python3 scripts/unicode_nfc_table.py > crates/lex-rt/src/nfc_table.rs

`tokenizer.json` asks for NFC and there is no normalisation in `std`.
The tables are Unicode character data, which is data rather than anyone's
code, and generating them here keeps a dependency out of the crate and
keeps the licence question from arising at all.

Two tables come out:

  CCC   canonical combining class, for the characters that have one.
        NFC reorders marks by it before composing.
  COMP  (first, second) -> composite, for the pairs that actually compose.
        Derived by asking `unicodedata` rather than by reading the
        decomposition field, which is how composition exclusions and
        singletons exclude themselves without a second table.
"""

import sys
import unicodedata

MAX = 0x110000


def main():
    ccc = [(c, unicodedata.combining(chr(c))) for c in range(MAX)
           if unicodedata.combining(chr(c))]

    comp = []
    for c in range(MAX):
        ch = chr(c)
        d = unicodedata.decomposition(ch)
        # Canonical (no "<compat>" tag) and a pair.
        if not d or d.startswith("<"):
            continue
        parts = d.split()
        if len(parts) != 2:
            continue
        a, b = int(parts[0], 16), int(parts[1], 16)
        # The composite must actually come back, which excludes the
        # composition exclusions without listing them.
        if unicodedata.normalize("NFC", chr(a) + chr(b)) == ch:
            comp.append((a, b, c))

    out = sys.stdout.write
    out("//! Canonical combining classes and compositions.\n//!\n")
    out("//! Generated by `scripts/unicode_nfc_table.py` from the Unicode\n")
    out("//! character database; do not edit. Unicode version "
        f"{unicodedata.unidata_version}.\n\n")
    out("/// Characters with a non-zero canonical combining class, sorted.\n")
    out(f"pub static CCC: [(u32, u8); {len(ccc)}] = [\n")
    for i in range(0, len(ccc), 8):
        out("    " + " ".join(f"({c:#x}, {k})," for c, k in ccc[i:i + 8]) + "\n")
    out("];\n\n")
    # Sorted by the pair, because that is the key it is searched by.
    # Emitted in composite order it looks sorted and is not, and a binary
    # search over it silently misses.
    comp.sort()
    out("/// `(first, second, composite)` for pairs that compose, sorted by pair.\n")
    out(f"pub static COMP: [(u32, u32, u32); {len(comp)}] = [\n")
    for i in range(0, len(comp), 4):
        out("    " + " ".join(f"({a:#x}, {b:#x}, {c:#x})," for a, b, c in comp[i:i + 4]) + "\n")
    out("];\n")
    print(f"{len(ccc)} combining classes, {len(comp)} compositions", file=sys.stderr)


if __name__ == "__main__":
    main()
