// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : matvec_nvfp4_17408x5120
// target : nvidia-ada
// launch : 2176 threadgroups x 256 threads
// tg mem : 0 B tiles + 32 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;

__constant__ float FP4_V[16] = {
    0.0f, 0.5f, 1.0f, 1.5f, 2.0f, 3.0f, 4.0f, 6.0f,
    -0.0f, -0.5f, -1.0f, -1.5f, -2.0f, -3.0f, -4.0f, -6.0f};
__device__ __forceinline__ float2 fp4_pair(uint b) {
    const uint w = b | (b << 12u);
    const uint bits = ((w & 0x00070007u) << 9u)
                    | ((w & 0x00080008u) << 12u);
    __half2 h;
    memcpy(&h, &bits, sizeof(h));
    return __half22float2(h);
}
__device__ __forceinline__ float fp8_e4m3(uint b) {
    const uint e = (b >> 3u) & 0xFu, m = b & 7u;
    const float sub = float(m) * 0.001953125f;
    uint subbits;
    memcpy(&subbits, &sub, sizeof(subbits));
    const uint bits = (e == 0u) ? subbits : (((e + 120u) << 23u) | (m << 20u));
    const uint out = bits | ((b & 0x80u) << 24u);
    float r;
    memcpy(&r, &out, sizeof(r));
    return r;
}

extern "C" __global__ void matvec_nvfp4_17408x5120(
    const float* __restrict__ p0_x,
    const char* __restrict__ p1_wq,
    const char* __restrict__ p2_ws,
    const float* __restrict__ p3_wgs,
    float* __restrict__ p4_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x, gid2 = blockIdx.y;
    __shared__ float scratch[8];
    const float fp4_lane = FP4_V[tid & 15u];
    float v1[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 8u) {
            v1[k] = float(0.0f);
        }
    }
    float v3[1];
    for (uint k = 0; k < 1u; ++k) v3[k] = v1[k];
    for (uint v2 = 0u; v2 < 1u; ++v2) {
        __syncthreads();
        {
            const uint o = tid / 32u, lane = tid % 32u;
            float s = 0.0f;
            if (o < 8u) {
                const uint i = o / 8u, j = o % 8u;
                const float rs = float(float(p3_wgs[(uint)(0 + 8 * gid) * 1u + ((j))]));
                for (uint p0 = lane * 16u; p0 < 5120u; p0 += 512u) {
                    const uint grp = j * 320u + p0 / 16u;
                    const float sg = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0 + 8 * gid) * 320u + (uint)(0 + 320 * v2) * 1u + ((grp))])) & 0xFFu) * rs;
                    float run = 0.0f;
                    for (uint u = 0; u < 16u; u += 2u) { const uint p = p0 + u; const uint bq = (uint)(uchar)(char(p1_wq[(uint)(0 + 8 * gid) * 2560u + (uint)(0 + 2560 * v2) * 1u + ((j * 2560u + p0 / 2u + u / 2u))])); const float2 w = fp4_pair(bq); run += float(float(p0_x[(uint)(0) * 5120u + (uint)(0 + 5120 * v2) * 1u + ((i * 5120u + p))])) * w.x + float(float(p0_x[(uint)(0) * 5120u + (uint)(0 + 5120 * v2) * 1u + ((i * 5120u + p + 1u))])) * w.y; }
                    s += run * (sg * 16384.0f);
                }
            }
            for (uint d = 16u; d > 0; d /= 2) s += __shfl_down_sync(0xffffffffu, s, d);
            if (o < 8u && lane == 0) scratch[0 + o] = s;
        }
        __syncthreads();
        float v9[1];
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 256u + tid;
            if (e < 8u) {
                v9[k] = float(scratch[0 + e]);
            }
        }
        float v10[1];
        for (uint k = 0; k < 1u; ++k) {
            const uint e = k * 256u + tid;
            if (e < 8u) {
                v10[k] = float(float(v3[k]) + float(v9[k]));
            }
        }
        for (uint k = 0; k < 1u; ++k) v3[k] = v10[k];
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 8u) {
            p4_y[((uint)(0) + ((e) / 8u % 1u)) * 17408u + ((uint)(0 + 8 * gid) + ((e) / 1u % 8u)) * 1u] = float(float(v3[k]));
        }
    }
}
