// Generated by lex-msl. Do not edit by hand.
// kernel : rmsnorm_f32
// op     : RmsNorm { dtype: F32, rows: 8, cols: 4096, eps: 1e-5 }
// target : apple-m-series (simd 32, threadgroup budget 32768 B)
// launch : 8 threadgroups x 256 threads, vec4
// tg mem : 32 B of 32768 B

#include <metal_stdlib>
using namespace metal;

kernel void rmsnorm_f32(
    device const float4 *x [[buffer(0)]],
    device const float4 *w [[buffer(1)]],
    device float4 *y [[buffer(2)]],
    uint row  [[threadgroup_position_in_grid]],
    uint tid  [[thread_position_in_threadgroup]],
    uint lane [[thread_index_in_simdgroup]],
    uint sg   [[simdgroup_index_in_threadgroup]])
{
    // One f32 partial per simdgroup: 32 B, checked against the target
    // table at plan time rather than discovered at pipeline creation.
    threadgroup float partial[8];

    // One threadgroup owns one row, so the row base is uniform across it.
    // The cast to ulong matters: rows * cols overflows 32 bits well before it
    // exhausts the memory of a Mac Studio.
    device const float4 *xr = x + (ulong)row * 1024u;
    device float4 *yr = y + (ulong)row * 1024u;

    // Pass 1: sum of squares, accumulated in f32 whatever the storage type.
    float acc = 0.0f;
    for (uint i = tid; i < 1024u; i += 256u) {
        float4 v = float4(xr[i]);
        acc += dot(v, v);
    }

    // Two-stage reduction: within each simdgroup, then across simdgroups.
    // `sg` is uniform within a simdgroup, so the guarded simd_sum below is
    // entered by all 32 lanes together.
    acc = simd_sum(acc);
    if (lane == 0u) { partial[sg] = acc; }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (sg == 0u) {
        float v = (lane < 8u) ? partial[lane] : 0.0f;
        v = simd_sum(v);
        if (lane == 0u) { partial[0] = v; }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);

    const float scale = rsqrt(partial[0] / 4096.0f + 1e-5f);

    // Pass 2: re-read the row, scale, write out. That re-read is the reason
    // this kernel cannot reach the copy ceiling once a row misses cache.
    // Staging the row in threadgroup memory instead is a scheduling decision,
    // not an algorithm change -- which is exactly the split P3 makes explicit.
    for (uint i = tid; i < 1024u; i += 256u) {
        yr[i] = float4(float4(xr[i]) * float4(w[i]) * scale);
    }
}
