// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : rmsnorm_4x4096_f32
// target : nvidia-ada
// launch : 4 threadgroups x 256 threads
// tg mem : 0 B tiles + 32 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;

extern "C" __global__ void rmsnorm_4x4096_f32(
    const float* __restrict__ p0_x,
    const float* __restrict__ p1_w,
    float* __restrict__ p2_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x;
    __shared__ float scratch[8];
    __syncthreads();
    {
        const uint o = tid / 256u, lane = tid % 256u;
        float s = 0.0f;
        if (o < 1u) for (uint j = lane; j < 4096u; j += 256u) s = s + float(float((float(float(p0_x[(uint)(0 + 1 * gid) * 4096u + (uint)(0) * 1u + ((o * 4096u + j))])) * float(float(p0_x[(uint)(0 + 1 * gid) * 4096u + (uint)(0) * 1u + ((o * 4096u + j))])))));
        for (uint d = 16u; d > 0; d /= 2) s = s + __shfl_down_sync(0xffffffffu, s, d);
        if (o < 1u && lane % 32u == 0) scratch[0 + o * 8u + lane / 32u] = s;
    }
    __syncthreads();
    float v3[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            float s = 0.0f;
            for (uint q = 0; q < 8u; ++q) s = s + scratch[0 + e * 8u + q];
            v3[k] = float(s);
        }
    }
    float v4[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            v4[k] = float(float(v3[k]) * 0.00024414063f);
        }
    }
    float v5[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            v5[k] = float(1e-5f);
        }
    }
    float v6[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            v6[k] = float(float(v4[k]) + float(v5[k]));
        }
    }
    float v7[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            v7[k] = float(rsqrtf(float(v6[k])));
        }
    }
    __syncthreads();
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            scratch[0 + e] = float(v7[k]);
        }
    }
    __syncthreads();
    float v8[16];
    for (uint k = 0; k < 16u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4096u) {
            v8[k] = float(float(float(p0_x[(uint)(0 + 1 * gid) * 4096u + (uint)(0) * 1u + ((e))])) * float((scratch + 0)[e / 4096u]));
        }
    }
    float v10[16];
    for (uint k = 0; k < 16u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4096u) {
            v10[k] = float(float(v8[k]) * float(float(p1_w[(uint)(0) * 4096u + (uint)(0) * 1u + ((e / 1u))])));
        }
    }
    for (uint k = 0; k < 16u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4096u) {
            p2_y[(uint)(0 + 1 * gid) * 4096u + (uint)(0) * 1u + (e)] = float(float(v10[k]));
        }
    }
}
